// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module kalman_hw_update_estimate (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        hw_filter_observation_model_rows,
        hw_filter_observation_model_cols,
        hw_filter_predicted_state_cols,
        hw_filter_observation_model_data_V_address0,
        hw_filter_observation_model_data_V_ce0,
        hw_filter_observation_model_data_V_q0,
        hw_filter_predicted_state_data_V_address0,
        hw_filter_predicted_state_data_V_ce0,
        hw_filter_predicted_state_data_V_q0,
        hw_filter_innovation_data_V_address0,
        hw_filter_innovation_data_V_ce0,
        hw_filter_innovation_data_V_we0,
        hw_filter_innovation_data_V_d0,
        hw_filter_innovation_data_V_q0,
        hw_filter_observation_rows,
        hw_filter_observation_cols,
        hw_filter_innovation_cols_i,
        hw_filter_innovation_cols_o,
        hw_filter_innovation_cols_o_ap_vld,
        hw_filter_observation_data_V_address0,
        hw_filter_observation_data_V_ce0,
        hw_filter_observation_data_V_q0,
        hw_filter_predicted_estimate_covariance_rows,
        hw_filter_vertical_scratch_rows_i,
        hw_filter_vertical_scratch_rows_o,
        hw_filter_vertical_scratch_rows_o_ap_vld,
        hw_filter_vertical_scratch_cols_i,
        hw_filter_vertical_scratch_cols_o,
        hw_filter_vertical_scratch_cols_o_ap_vld,
        hw_filter_predicted_estimate_covariance_cols,
        hw_filter_vertical_scratch_data_V_address0,
        hw_filter_vertical_scratch_data_V_ce0,
        hw_filter_vertical_scratch_data_V_we0,
        hw_filter_vertical_scratch_data_V_d0,
        hw_filter_vertical_scratch_data_V_q0,
        hw_filter_predicted_estimate_covariance_data_V_address0,
        hw_filter_predicted_estimate_covariance_data_V_ce0,
        hw_filter_predicted_estimate_covariance_data_V_q0,
        hw_filter_innovation_covariance_data_V_address0,
        hw_filter_innovation_covariance_data_V_ce0,
        hw_filter_innovation_covariance_data_V_we0,
        hw_filter_innovation_covariance_data_V_d0,
        hw_filter_innovation_covariance_data_V_q0,
        hw_filter_innovation_covariance_data_V_address1,
        hw_filter_innovation_covariance_data_V_ce1,
        hw_filter_innovation_covariance_data_V_we1,
        hw_filter_innovation_covariance_data_V_d1,
        hw_filter_innovation_covariance_data_V_q1,
        hw_filter_innovation_covariance_rows_i,
        hw_filter_innovation_covariance_rows_o,
        hw_filter_innovation_covariance_rows_o_ap_vld,
        hw_filter_innovation_covariance_cols_i,
        hw_filter_innovation_covariance_cols_o,
        hw_filter_innovation_covariance_cols_o_ap_vld,
        hw_filter_observation_noise_covariance_data_V_address0,
        hw_filter_observation_noise_covariance_data_V_ce0,
        hw_filter_observation_noise_covariance_data_V_q0,
        hw_filter_inverse_innovation_covariance_cols_i,
        hw_filter_inverse_innovation_covariance_cols_o,
        hw_filter_inverse_innovation_covariance_cols_o_ap_vld,
        hw_filter_inverse_innovation_covariance_data_V_address0,
        hw_filter_inverse_innovation_covariance_data_V_ce0,
        hw_filter_inverse_innovation_covariance_data_V_we0,
        hw_filter_inverse_innovation_covariance_data_V_d0,
        hw_filter_inverse_innovation_covariance_data_V_q0,
        hw_filter_inverse_innovation_covariance_data_V_address1,
        hw_filter_inverse_innovation_covariance_data_V_ce1,
        hw_filter_inverse_innovation_covariance_data_V_we1,
        hw_filter_inverse_innovation_covariance_data_V_d1,
        hw_filter_inverse_innovation_covariance_data_V_q1,
        hw_filter_optimal_gain_data_V_address0,
        hw_filter_optimal_gain_data_V_ce0,
        hw_filter_optimal_gain_data_V_we0,
        hw_filter_optimal_gain_data_V_d0,
        hw_filter_optimal_gain_data_V_q0,
        hw_filter_optimal_gain_rows_i,
        hw_filter_optimal_gain_rows_o,
        hw_filter_optimal_gain_rows_o_ap_vld,
        hw_filter_optimal_gain_cols_i,
        hw_filter_optimal_gain_cols_o,
        hw_filter_optimal_gain_cols_o_ap_vld,
        hw_filter_state_estimate_data_V_address0,
        hw_filter_state_estimate_data_V_ce0,
        hw_filter_state_estimate_data_V_we0,
        hw_filter_state_estimate_data_V_d0,
        hw_filter_state_estimate_data_V_q0,
        hw_filter_state_estimate_cols,
        hw_filter_state_estimate_cols_ap_vld,
        hw_filter_big_square_scratch_data_V_address0,
        hw_filter_big_square_scratch_data_V_ce0,
        hw_filter_big_square_scratch_data_V_we0,
        hw_filter_big_square_scratch_data_V_d0,
        hw_filter_big_square_scratch_data_V_q0,
        hw_filter_estimate_covariance_data_V_address0,
        hw_filter_estimate_covariance_data_V_ce0,
        hw_filter_estimate_covariance_data_V_we0,
        hw_filter_estimate_covariance_data_V_d0,
        hw_filter_estimate_covariance_rows,
        hw_filter_estimate_covariance_rows_ap_vld,
        hw_filter_estimate_covariance_cols,
        hw_filter_estimate_covariance_cols_ap_vld
);

parameter    ap_ST_fsm_state1 = 26'd1;
parameter    ap_ST_fsm_state2 = 26'd2;
parameter    ap_ST_fsm_state3 = 26'd4;
parameter    ap_ST_fsm_state4 = 26'd8;
parameter    ap_ST_fsm_state5 = 26'd16;
parameter    ap_ST_fsm_state6 = 26'd32;
parameter    ap_ST_fsm_state7 = 26'd64;
parameter    ap_ST_fsm_state8 = 26'd128;
parameter    ap_ST_fsm_state9 = 26'd256;
parameter    ap_ST_fsm_state10 = 26'd512;
parameter    ap_ST_fsm_state11 = 26'd1024;
parameter    ap_ST_fsm_state12 = 26'd2048;
parameter    ap_ST_fsm_state13 = 26'd4096;
parameter    ap_ST_fsm_state14 = 26'd8192;
parameter    ap_ST_fsm_state15 = 26'd16384;
parameter    ap_ST_fsm_state16 = 26'd32768;
parameter    ap_ST_fsm_state17 = 26'd65536;
parameter    ap_ST_fsm_state18 = 26'd131072;
parameter    ap_ST_fsm_state19 = 26'd262144;
parameter    ap_ST_fsm_state20 = 26'd524288;
parameter    ap_ST_fsm_state21 = 26'd1048576;
parameter    ap_ST_fsm_state22 = 26'd2097152;
parameter    ap_ST_fsm_state23 = 26'd4194304;
parameter    ap_ST_fsm_state24 = 26'd8388608;
parameter    ap_ST_fsm_state25 = 26'd16777216;
parameter    ap_ST_fsm_state26 = 26'd33554432;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] hw_filter_observation_model_rows;
input  [31:0] hw_filter_observation_model_cols;
input  [31:0] hw_filter_predicted_state_cols;
output  [3:0] hw_filter_observation_model_data_V_address0;
output   hw_filter_observation_model_data_V_ce0;
input  [31:0] hw_filter_observation_model_data_V_q0;
output  [3:0] hw_filter_predicted_state_data_V_address0;
output   hw_filter_predicted_state_data_V_ce0;
input  [31:0] hw_filter_predicted_state_data_V_q0;
output  [3:0] hw_filter_innovation_data_V_address0;
output   hw_filter_innovation_data_V_ce0;
output   hw_filter_innovation_data_V_we0;
output  [31:0] hw_filter_innovation_data_V_d0;
input  [31:0] hw_filter_innovation_data_V_q0;
input  [31:0] hw_filter_observation_rows;
input  [31:0] hw_filter_observation_cols;
input  [31:0] hw_filter_innovation_cols_i;
output  [31:0] hw_filter_innovation_cols_o;
output   hw_filter_innovation_cols_o_ap_vld;
output  [3:0] hw_filter_observation_data_V_address0;
output   hw_filter_observation_data_V_ce0;
input  [31:0] hw_filter_observation_data_V_q0;
input  [31:0] hw_filter_predicted_estimate_covariance_rows;
input  [31:0] hw_filter_vertical_scratch_rows_i;
output  [31:0] hw_filter_vertical_scratch_rows_o;
output   hw_filter_vertical_scratch_rows_o_ap_vld;
input  [31:0] hw_filter_vertical_scratch_cols_i;
output  [31:0] hw_filter_vertical_scratch_cols_o;
output   hw_filter_vertical_scratch_cols_o_ap_vld;
input  [31:0] hw_filter_predicted_estimate_covariance_cols;
output  [3:0] hw_filter_vertical_scratch_data_V_address0;
output   hw_filter_vertical_scratch_data_V_ce0;
output   hw_filter_vertical_scratch_data_V_we0;
output  [31:0] hw_filter_vertical_scratch_data_V_d0;
input  [31:0] hw_filter_vertical_scratch_data_V_q0;
output  [3:0] hw_filter_predicted_estimate_covariance_data_V_address0;
output   hw_filter_predicted_estimate_covariance_data_V_ce0;
input  [31:0] hw_filter_predicted_estimate_covariance_data_V_q0;
output  [3:0] hw_filter_innovation_covariance_data_V_address0;
output   hw_filter_innovation_covariance_data_V_ce0;
output   hw_filter_innovation_covariance_data_V_we0;
output  [31:0] hw_filter_innovation_covariance_data_V_d0;
input  [31:0] hw_filter_innovation_covariance_data_V_q0;
output  [3:0] hw_filter_innovation_covariance_data_V_address1;
output   hw_filter_innovation_covariance_data_V_ce1;
output   hw_filter_innovation_covariance_data_V_we1;
output  [31:0] hw_filter_innovation_covariance_data_V_d1;
input  [31:0] hw_filter_innovation_covariance_data_V_q1;
input  [31:0] hw_filter_innovation_covariance_rows_i;
output  [31:0] hw_filter_innovation_covariance_rows_o;
output   hw_filter_innovation_covariance_rows_o_ap_vld;
input  [31:0] hw_filter_innovation_covariance_cols_i;
output  [31:0] hw_filter_innovation_covariance_cols_o;
output   hw_filter_innovation_covariance_cols_o_ap_vld;
output  [3:0] hw_filter_observation_noise_covariance_data_V_address0;
output   hw_filter_observation_noise_covariance_data_V_ce0;
input  [31:0] hw_filter_observation_noise_covariance_data_V_q0;
input  [31:0] hw_filter_inverse_innovation_covariance_cols_i;
output  [31:0] hw_filter_inverse_innovation_covariance_cols_o;
output   hw_filter_inverse_innovation_covariance_cols_o_ap_vld;
output  [3:0] hw_filter_inverse_innovation_covariance_data_V_address0;
output   hw_filter_inverse_innovation_covariance_data_V_ce0;
output   hw_filter_inverse_innovation_covariance_data_V_we0;
output  [31:0] hw_filter_inverse_innovation_covariance_data_V_d0;
input  [31:0] hw_filter_inverse_innovation_covariance_data_V_q0;
output  [3:0] hw_filter_inverse_innovation_covariance_data_V_address1;
output   hw_filter_inverse_innovation_covariance_data_V_ce1;
output   hw_filter_inverse_innovation_covariance_data_V_we1;
output  [31:0] hw_filter_inverse_innovation_covariance_data_V_d1;
input  [31:0] hw_filter_inverse_innovation_covariance_data_V_q1;
output  [3:0] hw_filter_optimal_gain_data_V_address0;
output   hw_filter_optimal_gain_data_V_ce0;
output   hw_filter_optimal_gain_data_V_we0;
output  [31:0] hw_filter_optimal_gain_data_V_d0;
input  [31:0] hw_filter_optimal_gain_data_V_q0;
input  [31:0] hw_filter_optimal_gain_rows_i;
output  [31:0] hw_filter_optimal_gain_rows_o;
output   hw_filter_optimal_gain_rows_o_ap_vld;
input  [31:0] hw_filter_optimal_gain_cols_i;
output  [31:0] hw_filter_optimal_gain_cols_o;
output   hw_filter_optimal_gain_cols_o_ap_vld;
output  [3:0] hw_filter_state_estimate_data_V_address0;
output   hw_filter_state_estimate_data_V_ce0;
output   hw_filter_state_estimate_data_V_we0;
output  [31:0] hw_filter_state_estimate_data_V_d0;
input  [31:0] hw_filter_state_estimate_data_V_q0;
output  [31:0] hw_filter_state_estimate_cols;
output   hw_filter_state_estimate_cols_ap_vld;
output  [3:0] hw_filter_big_square_scratch_data_V_address0;
output   hw_filter_big_square_scratch_data_V_ce0;
output   hw_filter_big_square_scratch_data_V_we0;
output  [31:0] hw_filter_big_square_scratch_data_V_d0;
input  [31:0] hw_filter_big_square_scratch_data_V_q0;
output  [3:0] hw_filter_estimate_covariance_data_V_address0;
output   hw_filter_estimate_covariance_data_V_ce0;
output   hw_filter_estimate_covariance_data_V_we0;
output  [31:0] hw_filter_estimate_covariance_data_V_d0;
output  [31:0] hw_filter_estimate_covariance_rows;
output   hw_filter_estimate_covariance_rows_ap_vld;
output  [31:0] hw_filter_estimate_covariance_cols;
output   hw_filter_estimate_covariance_cols_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] hw_filter_observation_model_data_V_address0;
reg hw_filter_observation_model_data_V_ce0;
reg[3:0] hw_filter_predicted_state_data_V_address0;
reg hw_filter_predicted_state_data_V_ce0;
reg[3:0] hw_filter_innovation_data_V_address0;
reg hw_filter_innovation_data_V_ce0;
reg hw_filter_innovation_data_V_we0;
reg[31:0] hw_filter_innovation_data_V_d0;
reg[31:0] hw_filter_innovation_cols_o;
reg hw_filter_innovation_cols_o_ap_vld;
reg hw_filter_observation_data_V_ce0;
reg[31:0] hw_filter_vertical_scratch_rows_o;
reg hw_filter_vertical_scratch_rows_o_ap_vld;
reg[31:0] hw_filter_vertical_scratch_cols_o;
reg hw_filter_vertical_scratch_cols_o_ap_vld;
reg[3:0] hw_filter_vertical_scratch_data_V_address0;
reg hw_filter_vertical_scratch_data_V_ce0;
reg hw_filter_vertical_scratch_data_V_we0;
reg[31:0] hw_filter_vertical_scratch_data_V_d0;
reg[3:0] hw_filter_predicted_estimate_covariance_data_V_address0;
reg hw_filter_predicted_estimate_covariance_data_V_ce0;
reg[3:0] hw_filter_innovation_covariance_data_V_address0;
reg hw_filter_innovation_covariance_data_V_ce0;
reg hw_filter_innovation_covariance_data_V_we0;
reg[31:0] hw_filter_innovation_covariance_data_V_d0;
reg hw_filter_innovation_covariance_data_V_ce1;
reg hw_filter_innovation_covariance_data_V_we1;
reg[31:0] hw_filter_innovation_covariance_rows_o;
reg hw_filter_innovation_covariance_rows_o_ap_vld;
reg[31:0] hw_filter_innovation_covariance_cols_o;
reg hw_filter_innovation_covariance_cols_o_ap_vld;
reg hw_filter_observation_noise_covariance_data_V_ce0;
reg[31:0] hw_filter_inverse_innovation_covariance_cols_o;
reg hw_filter_inverse_innovation_covariance_cols_o_ap_vld;
reg[3:0] hw_filter_inverse_innovation_covariance_data_V_address0;
reg hw_filter_inverse_innovation_covariance_data_V_ce0;
reg hw_filter_inverse_innovation_covariance_data_V_we0;
reg hw_filter_inverse_innovation_covariance_data_V_ce1;
reg hw_filter_inverse_innovation_covariance_data_V_we1;
reg[3:0] hw_filter_optimal_gain_data_V_address0;
reg hw_filter_optimal_gain_data_V_ce0;
reg hw_filter_optimal_gain_data_V_we0;
reg[31:0] hw_filter_optimal_gain_rows_o;
reg hw_filter_optimal_gain_rows_o_ap_vld;
reg[31:0] hw_filter_optimal_gain_cols_o;
reg hw_filter_optimal_gain_cols_o_ap_vld;
reg[3:0] hw_filter_state_estimate_data_V_address0;
reg hw_filter_state_estimate_data_V_ce0;
reg hw_filter_state_estimate_data_V_we0;
reg[31:0] hw_filter_state_estimate_data_V_d0;
reg hw_filter_state_estimate_cols_ap_vld;
reg[3:0] hw_filter_big_square_scratch_data_V_address0;
reg hw_filter_big_square_scratch_data_V_ce0;
reg hw_filter_big_square_scratch_data_V_we0;
reg[31:0] hw_filter_big_square_scratch_data_V_d0;
reg hw_filter_estimate_covariance_data_V_ce0;
reg hw_filter_estimate_covariance_data_V_we0;
reg hw_filter_estimate_covariance_rows_ap_vld;
reg hw_filter_estimate_covariance_cols_ap_vld;

(* fsm_encoding = "none" *) reg   [25:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] reg_443;
wire    ap_CS_fsm_state10;
wire    grp_multiply_matrix_fu_409_ap_ready;
wire    grp_multiply_matrix_fu_409_ap_done;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state22;
reg   [31:0] reg_448;
wire   [31:0] add_ln93_fu_482_p2;
reg   [31:0] add_ln93_reg_1012;
wire    ap_CS_fsm_state3;
wire   [3:0] tmp_cast_fu_492_p3;
reg   [3:0] tmp_cast_reg_1017;
wire   [0:0] cmp91_i_fu_524_p2;
reg   [0:0] cmp91_i_reg_1031;
wire   [0:0] icmp_ln93_fu_500_p2;
wire   [4:0] add_ln95_fu_530_p2;
reg   [4:0] add_ln95_reg_1035;
wire    ap_CS_fsm_state4;
reg   [3:0] hw_filter_innovation_data_V_addr_reg_1040;
wire   [31:0] add_ln136_fu_567_p2;
reg   [31:0] add_ln136_reg_1053;
wire    ap_CS_fsm_state6;
wire   [3:0] tmp_11_cast_fu_577_p3;
reg   [3:0] tmp_11_cast_reg_1058;
wire   [4:0] add_ln138_fu_590_p2;
reg   [4:0] add_ln138_reg_1067;
wire    ap_CS_fsm_state7;
wire   [3:0] tmp_13_cast_fu_604_p3;
reg   [3:0] tmp_13_cast_reg_1072;
reg   [3:0] hw_filter_vertical_scratch_data_V_addr_reg_1077;
wire   [30:0] add_ln141_fu_631_p2;
reg   [30:0] add_ln141_reg_1085;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire   [30:0] add_ln80_fu_720_p2;
reg   [30:0] add_ln80_reg_1108;
wire    ap_CS_fsm_state11;
wire   [3:0] tmp_12_cast_fu_730_p3;
reg   [3:0] tmp_12_cast_reg_1113;
wire   [4:0] add_ln82_fu_748_p2;
reg   [4:0] add_ln82_reg_1121;
wire    ap_CS_fsm_state12;
reg   [3:0] hw_filter_innovation_covariance_data_V_addr_reg_1126;
wire   [30:0] add_ln80_1_fu_824_p2;
reg   [30:0] add_ln80_1_reg_1151;
wire    ap_CS_fsm_state19;
wire   [3:0] tmp_14_cast_fu_834_p3;
reg   [3:0] tmp_14_cast_reg_1156;
wire   [4:0] add_ln82_1_fu_862_p2;
reg   [4:0] add_ln82_1_reg_1170;
wire    ap_CS_fsm_state20;
reg   [3:0] hw_filter_state_estimate_data_V_addr_reg_1180;
wire   [31:0] add_ln103_fu_900_p2;
reg   [31:0] add_ln103_reg_1188;
wire    ap_CS_fsm_state23;
wire   [3:0] tmp_15_cast_fu_914_p3;
reg   [3:0] tmp_15_cast_reg_1193;
reg   [3:0] hw_filter_big_square_scratch_data_V_addr_reg_1198;
wire   [31:0] add_ln105_fu_939_p2;
reg   [31:0] add_ln105_reg_1206;
wire    ap_CS_fsm_state24;
reg   [3:0] hw_filter_big_square_scratch_data_V_addr_2_reg_1211;
wire   [0:0] icmp_ln107_fu_965_p2;
reg   [0:0] icmp_ln107_reg_1219;
wire   [0:0] icmp_ln105_fu_959_p2;
wire    grp_destructive_invert_matrix_fu_395_ap_start;
wire    grp_destructive_invert_matrix_fu_395_ap_done;
wire    grp_destructive_invert_matrix_fu_395_ap_idle;
wire    grp_destructive_invert_matrix_fu_395_ap_ready;
wire   [31:0] grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_cols;
wire    grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_cols_ap_vld;
wire   [3:0] grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_address0;
wire    grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_ce0;
wire    grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_we0;
wire   [31:0] grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_d0;
wire   [3:0] grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_address1;
wire    grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_ce1;
wire    grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_we1;
wire   [31:0] grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_d1;
wire   [3:0] grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_address0;
wire    grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_ce0;
wire    grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_we0;
wire   [31:0] grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_d0;
wire   [3:0] grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_address1;
wire    grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_ce1;
wire    grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_we1;
wire   [31:0] grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_d1;
wire    grp_multiply_matrix_fu_409_ap_start;
wire    grp_multiply_matrix_fu_409_ap_idle;
reg   [31:0] grp_multiply_matrix_fu_409_p_read;
reg   [31:0] grp_multiply_matrix_fu_409_p_read1;
wire   [3:0] grp_multiply_matrix_fu_409_a_data_address0;
wire    grp_multiply_matrix_fu_409_a_data_ce0;
reg   [31:0] grp_multiply_matrix_fu_409_a_data_q0;
reg   [31:0] grp_multiply_matrix_fu_409_p_read2;
wire   [3:0] grp_multiply_matrix_fu_409_b_data_address0;
wire    grp_multiply_matrix_fu_409_b_data_ce0;
reg   [31:0] grp_multiply_matrix_fu_409_b_data_q0;
wire   [3:0] grp_multiply_matrix_fu_409_c_data_address0;
wire    grp_multiply_matrix_fu_409_c_data_ce0;
wire    grp_multiply_matrix_fu_409_c_data_we0;
wire   [31:0] grp_multiply_matrix_fu_409_c_data_d0;
wire   [31:0] grp_multiply_matrix_fu_409_ap_return_0;
wire   [31:0] grp_multiply_matrix_fu_409_ap_return_1;
reg   [31:0] i_reg_260;
wire   [0:0] icmp_ln95_fu_555_p2;
wire    ap_CS_fsm_state2;
reg   [4:0] j_reg_271;
wire    ap_CS_fsm_state5;
reg   [31:0] i_7_reg_282;
wire   [0:0] icmp_ln138_fu_626_p2;
reg   [4:0] j_7_reg_293;
wire   [0:0] icmp_ln141_fu_665_p2;
wire   [0:0] icmp_ln136_fu_585_p2;
reg   [30:0] k_reg_304;
reg   [31:0] lhs_reg_315;
reg   [30:0] i_8_reg_328;
wire   [0:0] icmp_ln82_fu_773_p2;
reg   [4:0] j_8_reg_339;
wire    ap_CS_fsm_state13;
wire   [0:0] icmp_ln80_fu_742_p2;
reg   [30:0] i_9_reg_350;
wire   [0:0] icmp_ln82_1_fu_887_p2;
reg   [4:0] j_9_reg_361;
wire    ap_CS_fsm_state21;
wire   [0:0] icmp_ln80_1_fu_846_p2;
reg   [31:0] i_10_reg_372;
reg   [31:0] j_10_reg_384;
wire    ap_CS_fsm_state25;
wire   [0:0] icmp_ln103_fu_933_p2;
reg    grp_destructive_invert_matrix_fu_395_ap_start_reg;
wire    ap_CS_fsm_state14;
reg    grp_multiply_matrix_fu_409_ap_start_reg;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state26;
wire   [63:0] zext_ln703_fu_545_p1;
wire   [63:0] zext_ln140_fu_617_p1;
wire   [63:0] zext_ln1118_fu_646_p1;
wire   [63:0] zext_ln1116_fu_656_p1;
wire   [63:0] zext_ln703_1_fu_763_p1;
wire   [63:0] zext_ln703_2_fu_877_p1;
wire   [63:0] p_cast_fu_928_p1;
wire   [63:0] zext_ln703_3_fu_954_p1;
wire   [31:0] sub_ln703_fu_560_p2;
wire   [31:0] add_ln703_fu_779_p2;
wire   [31:0] add_ln703_1_fu_893_p2;
wire   [31:0] sub_ln703_2_fu_971_p2;
wire   [31:0] sub_ln703_1_fu_978_p2;
wire   [1:0] trunc_ln703_fu_488_p1;
wire   [3:0] trunc_ln703_2_fu_536_p1;
wire   [3:0] add_ln703_2_fu_540_p2;
wire   [31:0] zext_ln95_fu_551_p1;
wire   [1:0] trunc_ln1116_fu_573_p1;
wire   [1:0] trunc_ln1118_5_fu_600_p1;
wire   [3:0] trunc_ln1118_fu_596_p1;
wire   [3:0] add_ln140_fu_612_p2;
wire   [31:0] zext_ln138_fu_622_p1;
wire   [3:0] trunc_ln1118_6_fu_637_p1;
wire   [3:0] add_ln1118_fu_641_p2;
wire   [3:0] add_ln1116_fu_651_p2;
wire   [31:0] zext_ln141_fu_661_p1;
wire   [47:0] lhs_7_fu_684_p3;
wire   [47:0] r_V_8_fu_678_p2;
wire   [47:0] ret_V_fu_692_p2;
wire   [1:0] trunc_ln703_3_fu_726_p1;
wire   [31:0] zext_ln80_fu_738_p1;
wire   [3:0] trunc_ln703_4_fu_754_p1;
wire   [3:0] add_ln703_3_fu_758_p2;
wire   [31:0] zext_ln82_fu_769_p1;
wire   [1:0] trunc_ln703_5_fu_830_p1;
wire   [31:0] zext_ln80_1_fu_842_p1;
wire   [3:0] trunc_ln703_6_fu_868_p1;
wire   [3:0] add_ln703_4_fu_872_p2;
wire   [31:0] zext_ln82_1_fu_883_p1;
wire   [1:0] empty_34_fu_910_p1;
wire   [3:0] empty_33_fu_906_p1;
wire   [3:0] empty_35_fu_922_p2;
wire   [3:0] trunc_ln703_7_fu_945_p1;
wire   [3:0] add_ln703_5_fu_949_p2;
reg   [25:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 26'd1;
#0 grp_destructive_invert_matrix_fu_395_ap_start_reg = 1'b0;
#0 grp_multiply_matrix_fu_409_ap_start_reg = 1'b0;
end

kalman_hw_update_destructive_invert_matrix grp_destructive_invert_matrix_fu_395(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_destructive_invert_matrix_fu_395_ap_start),
    .ap_done(grp_destructive_invert_matrix_fu_395_ap_done),
    .ap_idle(grp_destructive_invert_matrix_fu_395_ap_idle),
    .ap_ready(grp_destructive_invert_matrix_fu_395_ap_ready),
    .hw_filter_innovation_covariance_rows(hw_filter_innovation_covariance_rows_i),
    .hw_filter_innovation_covariance_cols(hw_filter_innovation_covariance_cols_i),
    .hw_filter_inverse_innovation_covariance_cols(grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_cols),
    .hw_filter_inverse_innovation_covariance_cols_ap_vld(grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_cols_ap_vld),
    .hw_filter_inverse_innovation_covariance_data_V_address0(grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_address0),
    .hw_filter_inverse_innovation_covariance_data_V_ce0(grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_ce0),
    .hw_filter_inverse_innovation_covariance_data_V_we0(grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_we0),
    .hw_filter_inverse_innovation_covariance_data_V_d0(grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_d0),
    .hw_filter_inverse_innovation_covariance_data_V_q0(hw_filter_inverse_innovation_covariance_data_V_q0),
    .hw_filter_inverse_innovation_covariance_data_V_address1(grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_address1),
    .hw_filter_inverse_innovation_covariance_data_V_ce1(grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_ce1),
    .hw_filter_inverse_innovation_covariance_data_V_we1(grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_we1),
    .hw_filter_inverse_innovation_covariance_data_V_d1(grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_d1),
    .hw_filter_inverse_innovation_covariance_data_V_q1(hw_filter_inverse_innovation_covariance_data_V_q1),
    .hw_filter_innovation_covariance_data_V_address0(grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_address0),
    .hw_filter_innovation_covariance_data_V_ce0(grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_ce0),
    .hw_filter_innovation_covariance_data_V_we0(grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_we0),
    .hw_filter_innovation_covariance_data_V_d0(grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_d0),
    .hw_filter_innovation_covariance_data_V_q0(hw_filter_innovation_covariance_data_V_q0),
    .hw_filter_innovation_covariance_data_V_address1(grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_address1),
    .hw_filter_innovation_covariance_data_V_ce1(grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_ce1),
    .hw_filter_innovation_covariance_data_V_we1(grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_we1),
    .hw_filter_innovation_covariance_data_V_d1(grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_d1),
    .hw_filter_innovation_covariance_data_V_q1(hw_filter_innovation_covariance_data_V_q1)
);

kalman_hw_update_multiply_matrix grp_multiply_matrix_fu_409(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_multiply_matrix_fu_409_ap_start),
    .ap_done(grp_multiply_matrix_fu_409_ap_done),
    .ap_idle(grp_multiply_matrix_fu_409_ap_idle),
    .ap_ready(grp_multiply_matrix_fu_409_ap_ready),
    .p_read(grp_multiply_matrix_fu_409_p_read),
    .p_read1(grp_multiply_matrix_fu_409_p_read1),
    .a_data_address0(grp_multiply_matrix_fu_409_a_data_address0),
    .a_data_ce0(grp_multiply_matrix_fu_409_a_data_ce0),
    .a_data_q0(grp_multiply_matrix_fu_409_a_data_q0),
    .p_read2(grp_multiply_matrix_fu_409_p_read2),
    .b_data_address0(grp_multiply_matrix_fu_409_b_data_address0),
    .b_data_ce0(grp_multiply_matrix_fu_409_b_data_ce0),
    .b_data_q0(grp_multiply_matrix_fu_409_b_data_q0),
    .c_data_address0(grp_multiply_matrix_fu_409_c_data_address0),
    .c_data_ce0(grp_multiply_matrix_fu_409_c_data_ce0),
    .c_data_we0(grp_multiply_matrix_fu_409_c_data_we0),
    .c_data_d0(grp_multiply_matrix_fu_409_c_data_d0),
    .ap_return_0(grp_multiply_matrix_fu_409_ap_return_0),
    .ap_return_1(grp_multiply_matrix_fu_409_ap_return_1)
);

kalman_hw_update_mul_32s_32s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_1_1_U41(
    .din0(hw_filter_observation_model_data_V_q0),
    .din1(hw_filter_predicted_estimate_covariance_data_V_q0),
    .dout(r_V_8_fu_678_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_destructive_invert_matrix_fu_395_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln80_fu_742_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
            grp_destructive_invert_matrix_fu_395_ap_start_reg <= 1'b1;
        end else if ((grp_destructive_invert_matrix_fu_395_ap_ready == 1'b1)) begin
            grp_destructive_invert_matrix_fu_395_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_multiply_matrix_fu_409_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state15) | ((icmp_ln103_fu_933_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state23)) | ((icmp_ln80_1_fu_846_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19)) | ((icmp_ln136_fu_585_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
            grp_multiply_matrix_fu_409_ap_start_reg <= 1'b1;
        end else if ((grp_multiply_matrix_fu_409_ap_ready == 1'b1)) begin
            grp_multiply_matrix_fu_409_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state22) & (grp_multiply_matrix_fu_409_ap_done == 1'b1))) begin
        i_10_reg_372 <= 32'd0;
    end else if (((icmp_ln105_fu_959_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        i_10_reg_372 <= add_ln103_reg_1188;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln93_fu_500_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_7_reg_282 <= 32'd0;
    end else if (((icmp_ln138_fu_626_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        i_7_reg_282 <= add_ln136_reg_1053;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (grp_multiply_matrix_fu_409_ap_done == 1'b1))) begin
        i_8_reg_328 <= 31'd0;
    end else if (((icmp_ln82_fu_773_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        i_8_reg_328 <= add_ln80_reg_1108;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state18) & (grp_multiply_matrix_fu_409_ap_done == 1'b1))) begin
        i_9_reg_350 <= 31'd0;
    end else if (((icmp_ln82_1_fu_887_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state20))) begin
        i_9_reg_350 <= add_ln80_1_reg_1151;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_multiply_matrix_fu_409_ap_done == 1'b1))) begin
        i_reg_260 <= 32'd0;
    end else if (((icmp_ln95_fu_555_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        i_reg_260 <= add_ln93_reg_1012;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln103_fu_933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state23))) begin
        j_10_reg_384 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        j_10_reg_384 <= add_ln105_reg_1206;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln136_fu_585_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        j_7_reg_293 <= 5'd0;
    end else if (((1'b1 == ap_CS_fsm_state8) & ((icmp_ln141_fu_665_p2 == 1'd1) | (cmp91_i_reg_1031 == 1'd0)))) begin
        j_7_reg_293 <= add_ln138_reg_1067;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln80_fu_742_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        j_8_reg_339 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        j_8_reg_339 <= add_ln82_reg_1121;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln80_1_fu_846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        j_9_reg_361 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        j_9_reg_361 <= add_ln82_1_reg_1170;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln93_fu_500_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        j_reg_271 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        j_reg_271 <= add_ln95_reg_1035;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln138_fu_626_p2 == 1'd0) & (cmp91_i_reg_1031 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        k_reg_304 <= 31'd0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        k_reg_304 <= add_ln141_reg_1085;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln138_fu_626_p2 == 1'd0) & (cmp91_i_reg_1031 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        lhs_reg_315 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        lhs_reg_315 <= {{ret_V_fu_692_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        add_ln103_reg_1188 <= add_ln103_fu_900_p2;
        hw_filter_big_square_scratch_data_V_addr_reg_1198 <= p_cast_fu_928_p1;
        tmp_15_cast_reg_1193[3 : 2] <= tmp_15_cast_fu_914_p3[3 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        add_ln105_reg_1206 <= add_ln105_fu_939_p2;
        hw_filter_big_square_scratch_data_V_addr_2_reg_1211 <= zext_ln703_3_fu_954_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        add_ln136_reg_1053 <= add_ln136_fu_567_p2;
        tmp_11_cast_reg_1058[3 : 2] <= tmp_11_cast_fu_577_p3[3 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln138_reg_1067 <= add_ln138_fu_590_p2;
        hw_filter_vertical_scratch_data_V_addr_reg_1077 <= zext_ln140_fu_617_p1;
        tmp_13_cast_reg_1072[3 : 2] <= tmp_13_cast_fu_604_p3[3 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((cmp91_i_reg_1031 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        add_ln141_reg_1085 <= add_ln141_fu_631_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        add_ln80_1_reg_1151 <= add_ln80_1_fu_824_p2;
        tmp_14_cast_reg_1156[3 : 2] <= tmp_14_cast_fu_834_p3[3 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        add_ln80_reg_1108 <= add_ln80_fu_720_p2;
        tmp_12_cast_reg_1113[3 : 2] <= tmp_12_cast_fu_730_p3[3 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        add_ln82_1_reg_1170 <= add_ln82_1_fu_862_p2;
        hw_filter_state_estimate_data_V_addr_reg_1180 <= zext_ln703_2_fu_877_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        add_ln82_reg_1121 <= add_ln82_fu_748_p2;
        hw_filter_innovation_covariance_data_V_addr_reg_1126 <= zext_ln703_1_fu_763_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln93_reg_1012 <= add_ln93_fu_482_p2;
        tmp_cast_reg_1017[3 : 2] <= tmp_cast_fu_492_p3[3 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln95_reg_1035 <= add_ln95_fu_530_p2;
        hw_filter_innovation_data_V_addr_reg_1040 <= zext_ln703_fu_545_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln93_fu_500_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        cmp91_i_reg_1031 <= cmp91_i_fu_524_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln105_fu_959_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state24))) begin
        icmp_ln107_reg_1219 <= icmp_ln107_fu_965_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state22) & (grp_multiply_matrix_fu_409_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state18) & (grp_multiply_matrix_fu_409_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state16) & (grp_multiply_matrix_fu_409_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state10) & (grp_multiply_matrix_fu_409_ap_done == 1'b1)))) begin
        reg_443 <= grp_multiply_matrix_fu_409_ap_return_0;
        reg_448 <= grp_multiply_matrix_fu_409_ap_return_1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state26) & (grp_multiply_matrix_fu_409_ap_done == 1'b1)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) & (grp_multiply_matrix_fu_409_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        grp_multiply_matrix_fu_409_a_data_q0 = hw_filter_big_square_scratch_data_V_q0;
    end else if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state18))) begin
        grp_multiply_matrix_fu_409_a_data_q0 = hw_filter_optimal_gain_data_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_multiply_matrix_fu_409_a_data_q0 = hw_filter_vertical_scratch_data_V_q0;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state10))) begin
        grp_multiply_matrix_fu_409_a_data_q0 = hw_filter_observation_model_data_V_q0;
    end else begin
        grp_multiply_matrix_fu_409_a_data_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        grp_multiply_matrix_fu_409_b_data_q0 = hw_filter_predicted_estimate_covariance_data_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_multiply_matrix_fu_409_b_data_q0 = hw_filter_observation_model_data_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_multiply_matrix_fu_409_b_data_q0 = hw_filter_innovation_data_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_multiply_matrix_fu_409_b_data_q0 = hw_filter_inverse_innovation_covariance_data_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_multiply_matrix_fu_409_b_data_q0 = hw_filter_vertical_scratch_data_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_multiply_matrix_fu_409_b_data_q0 = hw_filter_predicted_state_data_V_q0;
    end else begin
        grp_multiply_matrix_fu_409_b_data_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_multiply_matrix_fu_409_p_read = hw_filter_optimal_gain_rows_i;
    end else if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state18))) begin
        grp_multiply_matrix_fu_409_p_read = reg_443;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_multiply_matrix_fu_409_p_read = hw_filter_vertical_scratch_rows_i;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state10))) begin
        grp_multiply_matrix_fu_409_p_read = hw_filter_observation_model_rows;
    end else begin
        grp_multiply_matrix_fu_409_p_read = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_multiply_matrix_fu_409_p_read1 = hw_filter_optimal_gain_cols_i;
    end else if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state18))) begin
        grp_multiply_matrix_fu_409_p_read1 = reg_448;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_multiply_matrix_fu_409_p_read1 = hw_filter_vertical_scratch_cols_i;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state10))) begin
        grp_multiply_matrix_fu_409_p_read1 = hw_filter_observation_model_cols;
    end else begin
        grp_multiply_matrix_fu_409_p_read1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        grp_multiply_matrix_fu_409_p_read2 = hw_filter_predicted_estimate_covariance_cols;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_multiply_matrix_fu_409_p_read2 = hw_filter_observation_model_cols;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_multiply_matrix_fu_409_p_read2 = hw_filter_innovation_cols_i;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_multiply_matrix_fu_409_p_read2 = hw_filter_inverse_innovation_covariance_cols_i;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_multiply_matrix_fu_409_p_read2 = hw_filter_observation_model_rows;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_multiply_matrix_fu_409_p_read2 = hw_filter_predicted_state_cols;
    end else begin
        grp_multiply_matrix_fu_409_p_read2 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln107_reg_1219 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
        hw_filter_big_square_scratch_data_V_address0 = hw_filter_big_square_scratch_data_V_addr_reg_1198;
    end else if (((icmp_ln107_reg_1219 == 1'd0) & (1'b1 == ap_CS_fsm_state25))) begin
        hw_filter_big_square_scratch_data_V_address0 = hw_filter_big_square_scratch_data_V_addr_2_reg_1211;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        hw_filter_big_square_scratch_data_V_address0 = zext_ln703_3_fu_954_p1;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        hw_filter_big_square_scratch_data_V_address0 = grp_multiply_matrix_fu_409_c_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        hw_filter_big_square_scratch_data_V_address0 = grp_multiply_matrix_fu_409_a_data_address0;
    end else begin
        hw_filter_big_square_scratch_data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) | ((icmp_ln107_reg_1219 == 1'd1) & (1'b1 == ap_CS_fsm_state25)) | ((icmp_ln107_reg_1219 == 1'd0) & (1'b1 == ap_CS_fsm_state25)))) begin
        hw_filter_big_square_scratch_data_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        hw_filter_big_square_scratch_data_V_ce0 = grp_multiply_matrix_fu_409_c_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        hw_filter_big_square_scratch_data_V_ce0 = grp_multiply_matrix_fu_409_a_data_ce0;
    end else begin
        hw_filter_big_square_scratch_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln107_reg_1219 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
        hw_filter_big_square_scratch_data_V_d0 = sub_ln703_1_fu_978_p2;
    end else if (((icmp_ln107_reg_1219 == 1'd0) & (1'b1 == ap_CS_fsm_state25))) begin
        hw_filter_big_square_scratch_data_V_d0 = sub_ln703_2_fu_971_p2;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        hw_filter_big_square_scratch_data_V_d0 = grp_multiply_matrix_fu_409_c_data_d0;
    end else begin
        hw_filter_big_square_scratch_data_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln107_reg_1219 == 1'd1) & (1'b1 == ap_CS_fsm_state25)) | ((icmp_ln107_reg_1219 == 1'd0) & (1'b1 == ap_CS_fsm_state25)))) begin
        hw_filter_big_square_scratch_data_V_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        hw_filter_big_square_scratch_data_V_we0 = grp_multiply_matrix_fu_409_c_data_we0;
    end else begin
        hw_filter_big_square_scratch_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) & (grp_multiply_matrix_fu_409_ap_done == 1'b1))) begin
        hw_filter_estimate_covariance_cols_ap_vld = 1'b1;
    end else begin
        hw_filter_estimate_covariance_cols_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        hw_filter_estimate_covariance_data_V_ce0 = grp_multiply_matrix_fu_409_c_data_ce0;
    end else begin
        hw_filter_estimate_covariance_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        hw_filter_estimate_covariance_data_V_we0 = grp_multiply_matrix_fu_409_c_data_we0;
    end else begin
        hw_filter_estimate_covariance_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) & (grp_multiply_matrix_fu_409_ap_done == 1'b1))) begin
        hw_filter_estimate_covariance_rows_ap_vld = 1'b1;
    end else begin
        hw_filter_estimate_covariance_rows_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        hw_filter_innovation_cols_o = hw_filter_observation_cols;
    end else begin
        hw_filter_innovation_cols_o = hw_filter_innovation_cols_i;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_multiply_matrix_fu_409_ap_done == 1'b1))) begin
        hw_filter_innovation_cols_o_ap_vld = 1'b1;
    end else begin
        hw_filter_innovation_cols_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        hw_filter_innovation_covariance_cols_o = grp_multiply_matrix_fu_409_ap_return_1;
    end else begin
        hw_filter_innovation_covariance_cols_o = hw_filter_innovation_covariance_cols_i;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (grp_multiply_matrix_fu_409_ap_done == 1'b1))) begin
        hw_filter_innovation_covariance_cols_o_ap_vld = 1'b1;
    end else begin
        hw_filter_innovation_covariance_cols_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        hw_filter_innovation_covariance_data_V_address0 = hw_filter_innovation_covariance_data_V_addr_reg_1126;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        hw_filter_innovation_covariance_data_V_address0 = zext_ln703_1_fu_763_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        hw_filter_innovation_covariance_data_V_address0 = grp_multiply_matrix_fu_409_c_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        hw_filter_innovation_covariance_data_V_address0 = grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_address0;
    end else begin
        hw_filter_innovation_covariance_data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        hw_filter_innovation_covariance_data_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        hw_filter_innovation_covariance_data_V_ce0 = grp_multiply_matrix_fu_409_c_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        hw_filter_innovation_covariance_data_V_ce0 = grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_ce0;
    end else begin
        hw_filter_innovation_covariance_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        hw_filter_innovation_covariance_data_V_ce1 = grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_ce1;
    end else begin
        hw_filter_innovation_covariance_data_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        hw_filter_innovation_covariance_data_V_d0 = add_ln703_fu_779_p2;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        hw_filter_innovation_covariance_data_V_d0 = grp_multiply_matrix_fu_409_c_data_d0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        hw_filter_innovation_covariance_data_V_d0 = grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_d0;
    end else begin
        hw_filter_innovation_covariance_data_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        hw_filter_innovation_covariance_data_V_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        hw_filter_innovation_covariance_data_V_we0 = grp_multiply_matrix_fu_409_c_data_we0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        hw_filter_innovation_covariance_data_V_we0 = grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_we0;
    end else begin
        hw_filter_innovation_covariance_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        hw_filter_innovation_covariance_data_V_we1 = grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_we1;
    end else begin
        hw_filter_innovation_covariance_data_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        hw_filter_innovation_covariance_rows_o = grp_multiply_matrix_fu_409_ap_return_0;
    end else begin
        hw_filter_innovation_covariance_rows_o = hw_filter_innovation_covariance_rows_i;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (grp_multiply_matrix_fu_409_ap_done == 1'b1))) begin
        hw_filter_innovation_covariance_rows_o_ap_vld = 1'b1;
    end else begin
        hw_filter_innovation_covariance_rows_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        hw_filter_innovation_data_V_address0 = hw_filter_innovation_data_V_addr_reg_1040;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        hw_filter_innovation_data_V_address0 = zext_ln703_fu_545_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hw_filter_innovation_data_V_address0 = grp_multiply_matrix_fu_409_c_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        hw_filter_innovation_data_V_address0 = grp_multiply_matrix_fu_409_b_data_address0;
    end else begin
        hw_filter_innovation_data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        hw_filter_innovation_data_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hw_filter_innovation_data_V_ce0 = grp_multiply_matrix_fu_409_c_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        hw_filter_innovation_data_V_ce0 = grp_multiply_matrix_fu_409_b_data_ce0;
    end else begin
        hw_filter_innovation_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        hw_filter_innovation_data_V_d0 = sub_ln703_fu_560_p2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hw_filter_innovation_data_V_d0 = grp_multiply_matrix_fu_409_c_data_d0;
    end else begin
        hw_filter_innovation_data_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        hw_filter_innovation_data_V_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hw_filter_innovation_data_V_we0 = grp_multiply_matrix_fu_409_c_data_we0;
    end else begin
        hw_filter_innovation_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_cols_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        hw_filter_inverse_innovation_covariance_cols_o = grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_cols;
    end else begin
        hw_filter_inverse_innovation_covariance_cols_o = hw_filter_inverse_innovation_covariance_cols_i;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        hw_filter_inverse_innovation_covariance_cols_o_ap_vld = grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_cols_ap_vld;
    end else begin
        hw_filter_inverse_innovation_covariance_cols_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        hw_filter_inverse_innovation_covariance_data_V_address0 = grp_multiply_matrix_fu_409_b_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        hw_filter_inverse_innovation_covariance_data_V_address0 = grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_address0;
    end else begin
        hw_filter_inverse_innovation_covariance_data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        hw_filter_inverse_innovation_covariance_data_V_ce0 = grp_multiply_matrix_fu_409_b_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        hw_filter_inverse_innovation_covariance_data_V_ce0 = grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_ce0;
    end else begin
        hw_filter_inverse_innovation_covariance_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        hw_filter_inverse_innovation_covariance_data_V_ce1 = grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_ce1;
    end else begin
        hw_filter_inverse_innovation_covariance_data_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        hw_filter_inverse_innovation_covariance_data_V_we0 = grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_we0;
    end else begin
        hw_filter_inverse_innovation_covariance_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        hw_filter_inverse_innovation_covariance_data_V_we1 = grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_we1;
    end else begin
        hw_filter_inverse_innovation_covariance_data_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hw_filter_observation_data_V_ce0 = 1'b1;
    end else begin
        hw_filter_observation_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        hw_filter_observation_model_data_V_address0 = zext_ln1118_fu_646_p1;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        hw_filter_observation_model_data_V_address0 = grp_multiply_matrix_fu_409_b_data_address0;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state10))) begin
        hw_filter_observation_model_data_V_address0 = grp_multiply_matrix_fu_409_a_data_address0;
    end else begin
        hw_filter_observation_model_data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        hw_filter_observation_model_data_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        hw_filter_observation_model_data_V_ce0 = grp_multiply_matrix_fu_409_b_data_ce0;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state10))) begin
        hw_filter_observation_model_data_V_ce0 = grp_multiply_matrix_fu_409_a_data_ce0;
    end else begin
        hw_filter_observation_model_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        hw_filter_observation_noise_covariance_data_V_ce0 = 1'b1;
    end else begin
        hw_filter_observation_noise_covariance_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        hw_filter_optimal_gain_cols_o = grp_multiply_matrix_fu_409_ap_return_1;
    end else begin
        hw_filter_optimal_gain_cols_o = hw_filter_optimal_gain_cols_i;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) & (grp_multiply_matrix_fu_409_ap_done == 1'b1))) begin
        hw_filter_optimal_gain_cols_o_ap_vld = 1'b1;
    end else begin
        hw_filter_optimal_gain_cols_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        hw_filter_optimal_gain_data_V_address0 = grp_multiply_matrix_fu_409_c_data_address0;
    end else if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state18))) begin
        hw_filter_optimal_gain_data_V_address0 = grp_multiply_matrix_fu_409_a_data_address0;
    end else begin
        hw_filter_optimal_gain_data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        hw_filter_optimal_gain_data_V_ce0 = grp_multiply_matrix_fu_409_c_data_ce0;
    end else if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state18))) begin
        hw_filter_optimal_gain_data_V_ce0 = grp_multiply_matrix_fu_409_a_data_ce0;
    end else begin
        hw_filter_optimal_gain_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        hw_filter_optimal_gain_data_V_we0 = grp_multiply_matrix_fu_409_c_data_we0;
    end else begin
        hw_filter_optimal_gain_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        hw_filter_optimal_gain_rows_o = grp_multiply_matrix_fu_409_ap_return_0;
    end else begin
        hw_filter_optimal_gain_rows_o = hw_filter_optimal_gain_rows_i;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) & (grp_multiply_matrix_fu_409_ap_done == 1'b1))) begin
        hw_filter_optimal_gain_rows_o_ap_vld = 1'b1;
    end else begin
        hw_filter_optimal_gain_rows_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        hw_filter_predicted_estimate_covariance_data_V_address0 = zext_ln1116_fu_656_p1;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        hw_filter_predicted_estimate_covariance_data_V_address0 = grp_multiply_matrix_fu_409_b_data_address0;
    end else begin
        hw_filter_predicted_estimate_covariance_data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        hw_filter_predicted_estimate_covariance_data_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        hw_filter_predicted_estimate_covariance_data_V_ce0 = grp_multiply_matrix_fu_409_b_data_ce0;
    end else begin
        hw_filter_predicted_estimate_covariance_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        hw_filter_predicted_state_data_V_address0 = zext_ln703_2_fu_877_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hw_filter_predicted_state_data_V_address0 = grp_multiply_matrix_fu_409_b_data_address0;
    end else begin
        hw_filter_predicted_state_data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        hw_filter_predicted_state_data_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hw_filter_predicted_state_data_V_ce0 = grp_multiply_matrix_fu_409_b_data_ce0;
    end else begin
        hw_filter_predicted_state_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) & (grp_multiply_matrix_fu_409_ap_done == 1'b1))) begin
        hw_filter_state_estimate_cols_ap_vld = 1'b1;
    end else begin
        hw_filter_state_estimate_cols_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        hw_filter_state_estimate_data_V_address0 = hw_filter_state_estimate_data_V_addr_reg_1180;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        hw_filter_state_estimate_data_V_address0 = zext_ln703_2_fu_877_p1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        hw_filter_state_estimate_data_V_address0 = grp_multiply_matrix_fu_409_c_data_address0;
    end else begin
        hw_filter_state_estimate_data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        hw_filter_state_estimate_data_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        hw_filter_state_estimate_data_V_ce0 = grp_multiply_matrix_fu_409_c_data_ce0;
    end else begin
        hw_filter_state_estimate_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        hw_filter_state_estimate_data_V_d0 = add_ln703_1_fu_893_p2;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        hw_filter_state_estimate_data_V_d0 = grp_multiply_matrix_fu_409_c_data_d0;
    end else begin
        hw_filter_state_estimate_data_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        hw_filter_state_estimate_data_V_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        hw_filter_state_estimate_data_V_we0 = grp_multiply_matrix_fu_409_c_data_we0;
    end else begin
        hw_filter_state_estimate_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_500_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        hw_filter_vertical_scratch_cols_o = hw_filter_observation_model_rows;
    end else begin
        hw_filter_vertical_scratch_cols_o = hw_filter_vertical_scratch_cols_i;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_500_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        hw_filter_vertical_scratch_cols_o_ap_vld = 1'b1;
    end else begin
        hw_filter_vertical_scratch_cols_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        hw_filter_vertical_scratch_data_V_address0 = hw_filter_vertical_scratch_data_V_addr_reg_1077;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        hw_filter_vertical_scratch_data_V_address0 = zext_ln140_fu_617_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        hw_filter_vertical_scratch_data_V_address0 = grp_multiply_matrix_fu_409_b_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        hw_filter_vertical_scratch_data_V_address0 = grp_multiply_matrix_fu_409_a_data_address0;
    end else begin
        hw_filter_vertical_scratch_data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        hw_filter_vertical_scratch_data_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        hw_filter_vertical_scratch_data_V_ce0 = grp_multiply_matrix_fu_409_b_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        hw_filter_vertical_scratch_data_V_ce0 = grp_multiply_matrix_fu_409_a_data_ce0;
    end else begin
        hw_filter_vertical_scratch_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        hw_filter_vertical_scratch_data_V_d0 = lhs_reg_315;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        hw_filter_vertical_scratch_data_V_d0 = 32'd0;
    end else begin
        hw_filter_vertical_scratch_data_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln138_fu_626_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)) | ((icmp_ln141_fu_665_p2 == 1'd1) & (cmp91_i_reg_1031 == 1'd1) & (1'b1 == ap_CS_fsm_state8)))) begin
        hw_filter_vertical_scratch_data_V_we0 = 1'b1;
    end else begin
        hw_filter_vertical_scratch_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_500_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        hw_filter_vertical_scratch_rows_o = hw_filter_predicted_estimate_covariance_rows;
    end else begin
        hw_filter_vertical_scratch_rows_o = hw_filter_vertical_scratch_rows_i;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_500_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        hw_filter_vertical_scratch_rows_o_ap_vld = 1'b1;
    end else begin
        hw_filter_vertical_scratch_rows_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_multiply_matrix_fu_409_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln93_fu_500_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln95_fu_555_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state6 : begin
            if (((icmp_ln136_fu_585_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((icmp_ln138_fu_626_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & ((icmp_ln141_fu_665_p2 == 1'd1) | (cmp91_i_reg_1031 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_multiply_matrix_fu_409_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((icmp_ln80_fu_742_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((icmp_ln82_fu_773_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state14 : begin
            if (((grp_destructive_invert_matrix_fu_395_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((1'b1 == ap_CS_fsm_state16) & (grp_multiply_matrix_fu_409_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if (((1'b1 == ap_CS_fsm_state18) & (grp_multiply_matrix_fu_409_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((icmp_ln80_1_fu_846_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state20 : begin
            if (((icmp_ln82_1_fu_887_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state22 : begin
            if (((1'b1 == ap_CS_fsm_state22) & (grp_multiply_matrix_fu_409_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state23 : begin
            if (((icmp_ln103_fu_933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state24 : begin
            if (((icmp_ln105_fu_959_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state26 : begin
            if (((1'b1 == ap_CS_fsm_state26) & (grp_multiply_matrix_fu_409_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln103_fu_900_p2 = (i_10_reg_372 + 32'd1);

assign add_ln105_fu_939_p2 = (j_10_reg_384 + 32'd1);

assign add_ln1116_fu_651_p2 = (tmp_11_cast_reg_1058 + trunc_ln1118_6_fu_637_p1);

assign add_ln1118_fu_641_p2 = (tmp_13_cast_reg_1072 + trunc_ln1118_6_fu_637_p1);

assign add_ln136_fu_567_p2 = (i_7_reg_282 + 32'd1);

assign add_ln138_fu_590_p2 = (j_7_reg_293 + 5'd1);

assign add_ln140_fu_612_p2 = (tmp_11_cast_reg_1058 + trunc_ln1118_fu_596_p1);

assign add_ln141_fu_631_p2 = (k_reg_304 + 31'd1);

assign add_ln703_1_fu_893_p2 = (hw_filter_predicted_state_data_V_q0 + hw_filter_state_estimate_data_V_q0);

assign add_ln703_2_fu_540_p2 = (tmp_cast_reg_1017 + trunc_ln703_2_fu_536_p1);

assign add_ln703_3_fu_758_p2 = (tmp_12_cast_reg_1113 + trunc_ln703_4_fu_754_p1);

assign add_ln703_4_fu_872_p2 = (tmp_14_cast_reg_1156 + trunc_ln703_6_fu_868_p1);

assign add_ln703_5_fu_949_p2 = (tmp_15_cast_reg_1193 + trunc_ln703_7_fu_945_p1);

assign add_ln703_fu_779_p2 = (hw_filter_observation_noise_covariance_data_V_q0 + hw_filter_innovation_covariance_data_V_q0);

assign add_ln80_1_fu_824_p2 = (i_9_reg_350 + 31'd1);

assign add_ln80_fu_720_p2 = (i_8_reg_328 + 31'd1);

assign add_ln82_1_fu_862_p2 = (j_9_reg_361 + 5'd1);

assign add_ln82_fu_748_p2 = (j_8_reg_339 + 5'd1);

assign add_ln93_fu_482_p2 = (i_reg_260 + 32'd1);

assign add_ln95_fu_530_p2 = (j_reg_271 + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign cmp91_i_fu_524_p2 = (($signed(hw_filter_predicted_estimate_covariance_cols) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign empty_33_fu_906_p1 = i_10_reg_372[3:0];

assign empty_34_fu_910_p1 = i_10_reg_372[1:0];

assign empty_35_fu_922_p2 = (tmp_15_cast_fu_914_p3 + empty_33_fu_906_p1);

assign grp_destructive_invert_matrix_fu_395_ap_start = grp_destructive_invert_matrix_fu_395_ap_start_reg;

assign grp_multiply_matrix_fu_409_ap_start = grp_multiply_matrix_fu_409_ap_start_reg;

assign hw_filter_estimate_covariance_cols = grp_multiply_matrix_fu_409_ap_return_1;

assign hw_filter_estimate_covariance_data_V_address0 = grp_multiply_matrix_fu_409_c_data_address0;

assign hw_filter_estimate_covariance_data_V_d0 = grp_multiply_matrix_fu_409_c_data_d0;

assign hw_filter_estimate_covariance_rows = grp_multiply_matrix_fu_409_ap_return_0;

assign hw_filter_innovation_covariance_data_V_address1 = grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_address1;

assign hw_filter_innovation_covariance_data_V_d1 = grp_destructive_invert_matrix_fu_395_hw_filter_innovation_covariance_data_V_d1;

assign hw_filter_inverse_innovation_covariance_data_V_address1 = grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_address1;

assign hw_filter_inverse_innovation_covariance_data_V_d0 = grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_d0;

assign hw_filter_inverse_innovation_covariance_data_V_d1 = grp_destructive_invert_matrix_fu_395_hw_filter_inverse_innovation_covariance_data_V_d1;

assign hw_filter_observation_data_V_address0 = zext_ln703_fu_545_p1;

assign hw_filter_observation_noise_covariance_data_V_address0 = zext_ln703_1_fu_763_p1;

assign hw_filter_optimal_gain_data_V_d0 = grp_multiply_matrix_fu_409_c_data_d0;

assign hw_filter_state_estimate_cols = grp_multiply_matrix_fu_409_ap_return_1;

assign icmp_ln103_fu_933_p2 = ((i_10_reg_372 == reg_443) ? 1'b1 : 1'b0);

assign icmp_ln105_fu_959_p2 = ((j_10_reg_384 == reg_448) ? 1'b1 : 1'b0);

assign icmp_ln107_fu_965_p2 = ((i_10_reg_372 == j_10_reg_384) ? 1'b1 : 1'b0);

assign icmp_ln136_fu_585_p2 = ((i_7_reg_282 == hw_filter_predicted_estimate_covariance_rows) ? 1'b1 : 1'b0);

assign icmp_ln138_fu_626_p2 = ((zext_ln138_fu_622_p1 == hw_filter_observation_model_rows) ? 1'b1 : 1'b0);

assign icmp_ln141_fu_665_p2 = ((zext_ln141_fu_661_p1 == hw_filter_predicted_estimate_covariance_cols) ? 1'b1 : 1'b0);

assign icmp_ln80_1_fu_846_p2 = (($signed(zext_ln80_1_fu_842_p1) < $signed(reg_443)) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_742_p2 = (($signed(zext_ln80_fu_738_p1) < $signed(reg_443)) ? 1'b1 : 1'b0);

assign icmp_ln82_1_fu_887_p2 = (($signed(zext_ln82_1_fu_883_p1) < $signed(reg_448)) ? 1'b1 : 1'b0);

assign icmp_ln82_fu_773_p2 = (($signed(zext_ln82_fu_769_p1) < $signed(reg_448)) ? 1'b1 : 1'b0);

assign icmp_ln93_fu_500_p2 = ((i_reg_260 == hw_filter_observation_rows) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_555_p2 = ((zext_ln95_fu_551_p1 == hw_filter_observation_cols) ? 1'b1 : 1'b0);

assign lhs_7_fu_684_p3 = {{lhs_reg_315}, {16'd0}};

assign p_cast_fu_928_p1 = empty_35_fu_922_p2;

assign ret_V_fu_692_p2 = (lhs_7_fu_684_p3 + r_V_8_fu_678_p2);

assign sub_ln703_1_fu_978_p2 = (32'd65536 - hw_filter_big_square_scratch_data_V_q0);

assign sub_ln703_2_fu_971_p2 = (32'd0 - hw_filter_big_square_scratch_data_V_q0);

assign sub_ln703_fu_560_p2 = (hw_filter_observation_data_V_q0 - hw_filter_innovation_data_V_q0);

assign tmp_11_cast_fu_577_p3 = {{trunc_ln1116_fu_573_p1}, {2'd0}};

assign tmp_12_cast_fu_730_p3 = {{trunc_ln703_3_fu_726_p1}, {2'd0}};

assign tmp_13_cast_fu_604_p3 = {{trunc_ln1118_5_fu_600_p1}, {2'd0}};

assign tmp_14_cast_fu_834_p3 = {{trunc_ln703_5_fu_830_p1}, {2'd0}};

assign tmp_15_cast_fu_914_p3 = {{empty_34_fu_910_p1}, {2'd0}};

assign tmp_cast_fu_492_p3 = {{trunc_ln703_fu_488_p1}, {2'd0}};

assign trunc_ln1116_fu_573_p1 = i_7_reg_282[1:0];

assign trunc_ln1118_5_fu_600_p1 = j_7_reg_293[1:0];

assign trunc_ln1118_6_fu_637_p1 = k_reg_304[3:0];

assign trunc_ln1118_fu_596_p1 = j_7_reg_293[3:0];

assign trunc_ln703_2_fu_536_p1 = j_reg_271[3:0];

assign trunc_ln703_3_fu_726_p1 = i_8_reg_328[1:0];

assign trunc_ln703_4_fu_754_p1 = j_8_reg_339[3:0];

assign trunc_ln703_5_fu_830_p1 = i_9_reg_350[1:0];

assign trunc_ln703_6_fu_868_p1 = j_9_reg_361[3:0];

assign trunc_ln703_7_fu_945_p1 = j_10_reg_384[3:0];

assign trunc_ln703_fu_488_p1 = i_reg_260[1:0];

assign zext_ln1116_fu_656_p1 = add_ln1116_fu_651_p2;

assign zext_ln1118_fu_646_p1 = add_ln1118_fu_641_p2;

assign zext_ln138_fu_622_p1 = j_7_reg_293;

assign zext_ln140_fu_617_p1 = add_ln140_fu_612_p2;

assign zext_ln141_fu_661_p1 = k_reg_304;

assign zext_ln703_1_fu_763_p1 = add_ln703_3_fu_758_p2;

assign zext_ln703_2_fu_877_p1 = add_ln703_4_fu_872_p2;

assign zext_ln703_3_fu_954_p1 = add_ln703_5_fu_949_p2;

assign zext_ln703_fu_545_p1 = add_ln703_2_fu_540_p2;

assign zext_ln80_1_fu_842_p1 = i_9_reg_350;

assign zext_ln80_fu_738_p1 = i_8_reg_328;

assign zext_ln82_1_fu_883_p1 = j_9_reg_361;

assign zext_ln82_fu_769_p1 = j_8_reg_339;

assign zext_ln95_fu_551_p1 = j_reg_271;

always @ (posedge ap_clk) begin
    tmp_cast_reg_1017[1:0] <= 2'b00;
    tmp_11_cast_reg_1058[1:0] <= 2'b00;
    tmp_13_cast_reg_1072[1:0] <= 2'b00;
    tmp_12_cast_reg_1113[1:0] <= 2'b00;
    tmp_14_cast_reg_1156[1:0] <= 2'b00;
    tmp_15_cast_reg_1193[1:0] <= 2'b00;
end

endmodule //kalman_hw_update_estimate
