// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module kalman_hw_update_init_matrix (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_data_address0,
        m_data_ce0,
        m_data_we0,
        m_data_d0,
        m_data_address1,
        m_data_ce1,
        m_data_we1,
        m_data_d1,
        m_rows_write,
        m_cols_write,
        ap_return_0,
        ap_return_1,
        ap_ce
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] m_data_address0;
output   m_data_ce0;
output   m_data_we0;
output  [31:0] m_data_d0;
output  [3:0] m_data_address1;
output   m_data_ce1;
output   m_data_we1;
output  [31:0] m_data_d1;
input  [1:0] m_rows_write;
input  [1:0] m_cols_write;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
input   ap_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] m_data_address0;
reg m_data_ce0;
reg m_data_we0;
reg[3:0] m_data_address1;
reg m_data_ce1;
reg m_data_we1;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [1:0] ap_port_reg_m_rows_write;
reg   [1:0] ap_port_reg_m_cols_write;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire   [31:0] m_rows_write_cast_fu_215_p1;
wire   [31:0] m_cols_write_cast_fu_211_p1;
reg   [7:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        ap_port_reg_m_cols_write <= m_cols_write;
        ap_port_reg_m_rows_write <= m_rows_write;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state8)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        m_data_address0 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        m_data_address0 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        m_data_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        m_data_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        m_data_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        m_data_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        m_data_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        m_data_address0 = 64'd1;
    end else begin
        m_data_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        m_data_address1 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        m_data_address1 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        m_data_address1 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        m_data_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        m_data_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        m_data_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        m_data_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        m_data_address1 = 64'd0;
    end else begin
        m_data_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state6) & (1'b1 == ap_ce)) | ((1'b1 == ap_CS_fsm_state5) & (1'b1 == ap_ce)) | ((1'b1 == ap_CS_fsm_state4) & (1'b1 == ap_ce)) | ((1'b1 == ap_CS_fsm_state3) & (1'b1 == ap_ce)) | ((1'b1 == ap_CS_fsm_state2) & (1'b1 == ap_ce)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state8)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state7)))) begin
        m_data_ce0 = 1'b1;
    end else begin
        m_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state6) & (1'b1 == ap_ce)) | ((1'b1 == ap_CS_fsm_state5) & (1'b1 == ap_ce)) | ((1'b1 == ap_CS_fsm_state4) & (1'b1 == ap_ce)) | ((1'b1 == ap_CS_fsm_state3) & (1'b1 == ap_ce)) | ((1'b1 == ap_CS_fsm_state2) & (1'b1 == ap_ce)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state8)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state7)))) begin
        m_data_ce1 = 1'b1;
    end else begin
        m_data_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state6) & (1'b1 == ap_ce)) | ((1'b1 == ap_CS_fsm_state5) & (1'b1 == ap_ce)) | ((1'b1 == ap_CS_fsm_state4) & (1'b1 == ap_ce)) | ((1'b1 == ap_CS_fsm_state3) & (1'b1 == ap_ce)) | ((1'b1 == ap_CS_fsm_state2) & (1'b1 == ap_ce)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state8)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state7)))) begin
        m_data_we0 = 1'b1;
    end else begin
        m_data_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state6) & (1'b1 == ap_ce)) | ((1'b1 == ap_CS_fsm_state5) & (1'b1 == ap_ce)) | ((1'b1 == ap_CS_fsm_state4) & (1'b1 == ap_ce)) | ((1'b1 == ap_CS_fsm_state3) & (1'b1 == ap_ce)) | ((1'b1 == ap_CS_fsm_state2) & (1'b1 == ap_ce)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state8)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state7)))) begin
        m_data_we1 = 1'b1;
    end else begin
        m_data_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b1 == ap_ce))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (1'b1 == ap_ce))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (1'b1 == ap_ce))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (1'b1 == ap_ce))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (1'b1 == ap_ce))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_return_0 = m_rows_write_cast_fu_215_p1;

assign ap_return_1 = m_cols_write_cast_fu_211_p1;

assign m_cols_write_cast_fu_211_p1 = ap_port_reg_m_cols_write;

assign m_data_d0 = 32'd0;

assign m_data_d1 = 32'd0;

assign m_rows_write_cast_fu_215_p1 = ap_port_reg_m_rows_write;

endmodule //kalman_hw_update_init_matrix
