// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module kalman_hw_update_destructive_invert_matrix (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        hw_filter_innovation_covariance_rows,
        hw_filter_innovation_covariance_cols,
        hw_filter_inverse_innovation_covariance_cols,
        hw_filter_inverse_innovation_covariance_cols_ap_vld,
        hw_filter_inverse_innovation_covariance_data_V_address0,
        hw_filter_inverse_innovation_covariance_data_V_ce0,
        hw_filter_inverse_innovation_covariance_data_V_we0,
        hw_filter_inverse_innovation_covariance_data_V_d0,
        hw_filter_inverse_innovation_covariance_data_V_q0,
        hw_filter_inverse_innovation_covariance_data_V_address1,
        hw_filter_inverse_innovation_covariance_data_V_ce1,
        hw_filter_inverse_innovation_covariance_data_V_we1,
        hw_filter_inverse_innovation_covariance_data_V_d1,
        hw_filter_inverse_innovation_covariance_data_V_q1,
        hw_filter_innovation_covariance_data_V_address0,
        hw_filter_innovation_covariance_data_V_ce0,
        hw_filter_innovation_covariance_data_V_we0,
        hw_filter_innovation_covariance_data_V_d0,
        hw_filter_innovation_covariance_data_V_q0,
        hw_filter_innovation_covariance_data_V_address1,
        hw_filter_innovation_covariance_data_V_ce1,
        hw_filter_innovation_covariance_data_V_we1,
        hw_filter_innovation_covariance_data_V_d1,
        hw_filter_innovation_covariance_data_V_q1
);

parameter    ap_ST_fsm_state1 = 61'd1;
parameter    ap_ST_fsm_state2 = 61'd2;
parameter    ap_ST_fsm_state3 = 61'd4;
parameter    ap_ST_fsm_state4 = 61'd8;
parameter    ap_ST_fsm_state5 = 61'd16;
parameter    ap_ST_fsm_state6 = 61'd32;
parameter    ap_ST_fsm_state7 = 61'd64;
parameter    ap_ST_fsm_state8 = 61'd128;
parameter    ap_ST_fsm_state9 = 61'd256;
parameter    ap_ST_fsm_state10 = 61'd512;
parameter    ap_ST_fsm_state11 = 61'd1024;
parameter    ap_ST_fsm_state12 = 61'd2048;
parameter    ap_ST_fsm_state13 = 61'd4096;
parameter    ap_ST_fsm_state14 = 61'd8192;
parameter    ap_ST_fsm_state15 = 61'd16384;
parameter    ap_ST_fsm_state16 = 61'd32768;
parameter    ap_ST_fsm_state17 = 61'd65536;
parameter    ap_ST_fsm_state18 = 61'd131072;
parameter    ap_ST_fsm_state19 = 61'd262144;
parameter    ap_ST_fsm_state20 = 61'd524288;
parameter    ap_ST_fsm_state21 = 61'd1048576;
parameter    ap_ST_fsm_state22 = 61'd2097152;
parameter    ap_ST_fsm_state23 = 61'd4194304;
parameter    ap_ST_fsm_state24 = 61'd8388608;
parameter    ap_ST_fsm_state25 = 61'd16777216;
parameter    ap_ST_fsm_state26 = 61'd33554432;
parameter    ap_ST_fsm_state27 = 61'd67108864;
parameter    ap_ST_fsm_state28 = 61'd134217728;
parameter    ap_ST_fsm_state29 = 61'd268435456;
parameter    ap_ST_fsm_state30 = 61'd536870912;
parameter    ap_ST_fsm_state31 = 61'd1073741824;
parameter    ap_ST_fsm_state32 = 61'd2147483648;
parameter    ap_ST_fsm_state33 = 61'd4294967296;
parameter    ap_ST_fsm_state34 = 61'd8589934592;
parameter    ap_ST_fsm_state35 = 61'd17179869184;
parameter    ap_ST_fsm_state36 = 61'd34359738368;
parameter    ap_ST_fsm_state37 = 61'd68719476736;
parameter    ap_ST_fsm_state38 = 61'd137438953472;
parameter    ap_ST_fsm_state39 = 61'd274877906944;
parameter    ap_ST_fsm_state40 = 61'd549755813888;
parameter    ap_ST_fsm_state41 = 61'd1099511627776;
parameter    ap_ST_fsm_state42 = 61'd2199023255552;
parameter    ap_ST_fsm_state43 = 61'd4398046511104;
parameter    ap_ST_fsm_state44 = 61'd8796093022208;
parameter    ap_ST_fsm_state45 = 61'd17592186044416;
parameter    ap_ST_fsm_state46 = 61'd35184372088832;
parameter    ap_ST_fsm_state47 = 61'd70368744177664;
parameter    ap_ST_fsm_state48 = 61'd140737488355328;
parameter    ap_ST_fsm_state49 = 61'd281474976710656;
parameter    ap_ST_fsm_state50 = 61'd562949953421312;
parameter    ap_ST_fsm_state51 = 61'd1125899906842624;
parameter    ap_ST_fsm_state52 = 61'd2251799813685248;
parameter    ap_ST_fsm_state53 = 61'd4503599627370496;
parameter    ap_ST_fsm_state54 = 61'd9007199254740992;
parameter    ap_ST_fsm_state55 = 61'd18014398509481984;
parameter    ap_ST_fsm_state56 = 61'd36028797018963968;
parameter    ap_ST_fsm_state57 = 61'd72057594037927936;
parameter    ap_ST_fsm_state58 = 61'd144115188075855872;
parameter    ap_ST_fsm_state59 = 61'd288230376151711744;
parameter    ap_ST_fsm_state60 = 61'd576460752303423488;
parameter    ap_ST_fsm_state61 = 61'd1152921504606846976;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] hw_filter_innovation_covariance_rows;
input  [31:0] hw_filter_innovation_covariance_cols;
output  [31:0] hw_filter_inverse_innovation_covariance_cols;
output   hw_filter_inverse_innovation_covariance_cols_ap_vld;
output  [3:0] hw_filter_inverse_innovation_covariance_data_V_address0;
output   hw_filter_inverse_innovation_covariance_data_V_ce0;
output   hw_filter_inverse_innovation_covariance_data_V_we0;
output  [31:0] hw_filter_inverse_innovation_covariance_data_V_d0;
input  [31:0] hw_filter_inverse_innovation_covariance_data_V_q0;
output  [3:0] hw_filter_inverse_innovation_covariance_data_V_address1;
output   hw_filter_inverse_innovation_covariance_data_V_ce1;
output   hw_filter_inverse_innovation_covariance_data_V_we1;
output  [31:0] hw_filter_inverse_innovation_covariance_data_V_d1;
input  [31:0] hw_filter_inverse_innovation_covariance_data_V_q1;
output  [3:0] hw_filter_innovation_covariance_data_V_address0;
output   hw_filter_innovation_covariance_data_V_ce0;
output   hw_filter_innovation_covariance_data_V_we0;
output  [31:0] hw_filter_innovation_covariance_data_V_d0;
input  [31:0] hw_filter_innovation_covariance_data_V_q0;
output  [3:0] hw_filter_innovation_covariance_data_V_address1;
output   hw_filter_innovation_covariance_data_V_ce1;
output   hw_filter_innovation_covariance_data_V_we1;
output  [31:0] hw_filter_innovation_covariance_data_V_d1;
input  [31:0] hw_filter_innovation_covariance_data_V_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg hw_filter_inverse_innovation_covariance_cols_ap_vld;
reg[3:0] hw_filter_inverse_innovation_covariance_data_V_address0;
reg hw_filter_inverse_innovation_covariance_data_V_ce0;
reg hw_filter_inverse_innovation_covariance_data_V_we0;
reg[31:0] hw_filter_inverse_innovation_covariance_data_V_d0;
reg[3:0] hw_filter_inverse_innovation_covariance_data_V_address1;
reg hw_filter_inverse_innovation_covariance_data_V_ce1;
reg hw_filter_inverse_innovation_covariance_data_V_we1;
reg[3:0] hw_filter_innovation_covariance_data_V_address0;
reg hw_filter_innovation_covariance_data_V_ce0;
reg hw_filter_innovation_covariance_data_V_we0;
reg[31:0] hw_filter_innovation_covariance_data_V_d0;
reg[3:0] hw_filter_innovation_covariance_data_V_address1;
reg hw_filter_innovation_covariance_data_V_ce1;
reg hw_filter_innovation_covariance_data_V_we1;

(* fsm_encoding = "none" *) reg   [60:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln46_fu_368_p2;
reg   [0:0] icmp_ln46_reg_966;
wire   [63:0] zext_ln46_fu_374_p1;
reg   [63:0] zext_ln46_reg_970;
wire   [30:0] trunc_ln46_fu_378_p1;
reg   [30:0] trunc_ln46_reg_975;
wire   [30:0] add_ln46_fu_382_p2;
reg   [30:0] add_ln46_reg_981;
wire    ap_CS_fsm_state2;
wire   [3:0] tmp_cast_fu_392_p3;
reg   [3:0] tmp_cast_reg_986;
wire   [0:0] cmp12_i_fu_405_p2;
reg   [0:0] cmp12_i_reg_994;
wire   [0:0] icmp_ln46_4_fu_400_p2;
wire   [4:0] add_ln48_fu_410_p2;
wire    ap_CS_fsm_state3;
wire   [63:0] zext_ln200_fu_458_p1;
reg   [63:0] zext_ln200_reg_1006;
wire    ap_CS_fsm_state4;
wire   [3:0] trunc_ln1498_fu_462_p1;
reg   [3:0] trunc_ln1498_reg_1011;
wire   [3:0] tmp_16_cast_fu_470_p3;
reg   [3:0] tmp_16_cast_reg_1017;
reg   [3:0] hw_filter_innovation_covariance_data_V_addr_reg_1027;
wire   [31:0] zext_ln200_1_fu_489_p1;
reg   [31:0] zext_ln200_1_reg_1032;
wire   [0:0] icmp_ln213_fu_493_p2;
reg   [0:0] icmp_ln213_reg_1037;
wire   [30:0] add_ln213_fu_498_p2;
reg   [30:0] add_ln213_reg_1041;
wire   [0:0] grp_fu_348_p2;
reg   [0:0] icmp_ln1498_reg_1046;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire   [31:0] r_fu_526_p2;
reg   [31:0] r_reg_1055;
wire   [0:0] icmp_ln217_fu_532_p2;
reg   [0:0] icmp_ln217_reg_1061;
wire   [63:0] add_ln217_fu_537_p2;
wire    ap_CS_fsm_state7;
wire   [3:0] tmp_19_cast_fu_557_p3;
reg   [3:0] tmp_19_cast_reg_1076;
wire   [0:0] icmp_ln222_fu_548_p2;
wire   [4:0] add_ln184_fu_565_p2;
reg   [4:0] add_ln184_reg_1082;
wire    ap_CS_fsm_state8;
reg   [3:0] hw_filter_innovation_covariance_data_V_addr_2_reg_1087;
reg   [3:0] hw_filter_innovation_covariance_data_V_addr_3_reg_1092;
wire   [4:0] add_ln184_1_fu_604_p2;
reg   [4:0] add_ln184_1_reg_1100;
wire    ap_CS_fsm_state11;
reg   [3:0] hw_filter_inverse_innovation_covariance_data_V_addr_1_reg_1105;
reg   [3:0] hw_filter_inverse_innovation_covariance_data_V_addr_2_reg_1110;
wire    ap_CS_fsm_state14;
wire  signed [47:0] sext_ln193_fu_657_p1;
reg  signed [47:0] sext_ln193_reg_1123;
wire    ap_CS_fsm_state51;
wire   [4:0] add_ln193_fu_661_p2;
reg   [4:0] add_ln193_reg_1129;
wire    ap_CS_fsm_state52;
reg   [3:0] hw_filter_innovation_covariance_data_V_addr_4_reg_1134;
wire   [4:0] add_ln193_1_fu_710_p2;
reg   [4:0] add_ln193_1_reg_1142;
wire    ap_CS_fsm_state54;
reg   [3:0] hw_filter_inverse_innovation_covariance_data_V_addr_3_reg_1147;
wire   [30:0] add_ln233_fu_759_p2;
reg   [30:0] add_ln233_reg_1155;
wire    ap_CS_fsm_state56;
wire   [3:0] tmp_20_cast_fu_769_p3;
reg   [3:0] tmp_20_cast_reg_1160;
wire   [0:0] icmp_ln235_fu_792_p2;
reg   [0:0] icmp_ln235_reg_1174;
wire   [0:0] icmp_ln233_fu_787_p2;
wire   [31:0] add_ln213_1_fu_798_p2;
wire  signed [47:0] sext_ln201_fu_810_p1;
reg  signed [47:0] sext_ln201_reg_1183;
wire    ap_CS_fsm_state57;
wire   [4:0] add_ln201_fu_814_p2;
reg   [4:0] add_ln201_reg_1189;
wire    ap_CS_fsm_state58;
reg   [3:0] hw_filter_innovation_covariance_data_V_addr_7_reg_1199;
wire   [4:0] add_ln201_1_fu_887_p2;
reg   [4:0] add_ln201_1_reg_1208;
wire    ap_CS_fsm_state60;
reg   [3:0] hw_filter_inverse_innovation_covariance_data_V_addr_5_reg_1218;
reg   [30:0] i_reg_196;
wire   [0:0] icmp_ln48_fu_438_p2;
reg   [4:0] j_reg_208;
reg   [30:0] r2_2_reg_219;
reg   [31:0] indvars_iv_reg_231;
reg   [63:0] r_1_reg_243;
reg   [31:0] r_04_in_reg_253;
wire   [31:0] trunc_ln219_fu_543_p1;
reg   [31:0] ap_phi_mux_r2_phi_fu_265_p4;
reg   [31:0] r2_reg_262;
reg   [4:0] j_11_reg_271;
wire    ap_CS_fsm_state10;
reg   [4:0] j_12_reg_282;
wire    ap_CS_fsm_state13;
wire   [0:0] icmp_ln184_fu_599_p2;
reg   [4:0] j_13_reg_293;
wire    ap_CS_fsm_state53;
reg   [4:0] j_14_reg_304;
wire    ap_CS_fsm_state55;
wire   [0:0] icmp_ln193_fu_685_p2;
reg   [30:0] r1_reg_315;
wire   [0:0] icmp_ln193_1_fu_734_p2;
wire   [0:0] icmp_ln201_1_fu_921_p2;
reg   [4:0] j_16_reg_326;
wire    ap_CS_fsm_state59;
reg   [4:0] j_17_reg_337;
wire    ap_CS_fsm_state61;
wire   [0:0] icmp_ln201_fu_848_p2;
wire   [63:0] zext_ln50_fu_425_p1;
wire   [63:0] zext_ln1498_fu_484_p1;
wire   [63:0] zext_ln1499_fu_521_p1;
wire   [63:0] zext_ln186_fu_580_p1;
wire   [63:0] zext_ln187_fu_590_p1;
wire   [63:0] zext_ln186_1_fu_619_p1;
wire   [63:0] zext_ln187_1_fu_629_p1;
wire   [63:0] zext_ln1116_fu_676_p1;
wire   [63:0] zext_ln1116_3_fu_725_p1;
wire   [63:0] zext_ln703_fu_782_p1;
wire   [63:0] zext_ln1118_fu_829_p1;
wire   [63:0] zext_ln727_fu_839_p1;
wire   [63:0] zext_ln1118_3_fu_902_p1;
wire   [63:0] zext_ln727_1_fu_912_p1;
wire   [31:0] select_ln50_fu_449_p3;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state9;
wire   [1:0] trunc_ln50_fu_388_p1;
wire   [3:0] trunc_ln50_6_fu_416_p1;
wire   [3:0] add_ln50_fu_420_p2;
wire   [31:0] zext_ln48_4_fu_434_p1;
wire   [30:0] zext_ln48_fu_430_p1;
wire   [0:0] icmp_ln50_fu_443_p2;
wire   [1:0] trunc_ln1498_1_fu_466_p1;
wire   [3:0] add_ln1498_fu_478_p2;
wire   [1:0] trunc_ln1499_fu_504_p1;
wire   [3:0] tmp_18_cast_fu_508_p3;
wire   [3:0] add_ln1499_fu_516_p2;
wire   [1:0] trunc_ln187_fu_553_p1;
wire   [3:0] trunc_ln186_fu_571_p1;
wire   [3:0] add_ln186_fu_575_p2;
wire   [3:0] add_ln187_fu_585_p2;
wire   [31:0] zext_ln184_fu_595_p1;
wire   [3:0] trunc_ln186_1_fu_610_p1;
wire   [3:0] add_ln186_1_fu_614_p2;
wire   [3:0] add_ln187_1_fu_624_p2;
wire   [31:0] zext_ln184_1_fu_634_p1;
wire   [31:0] grp_fu_647_p2;
wire   [31:0] scalar_V_fu_653_p1;
wire   [3:0] trunc_ln1116_fu_667_p1;
wire   [3:0] add_ln1116_fu_671_p2;
wire   [31:0] zext_ln193_fu_681_p1;
wire  signed [31:0] r_V_9_fu_694_p1;
wire   [47:0] r_V_9_fu_694_p2;
wire   [3:0] trunc_ln1116_4_fu_716_p1;
wire   [3:0] add_ln1116_3_fu_720_p2;
wire   [31:0] zext_ln193_1_fu_730_p1;
wire  signed [31:0] r_V_11_fu_743_p1;
wire   [47:0] r_V_11_fu_743_p2;
wire   [1:0] trunc_ln703_fu_765_p1;
wire   [3:0] add_ln703_fu_777_p2;
wire   [31:0] scalar_V_2_fu_804_p2;
wire   [3:0] trunc_ln1118_fu_820_p1;
wire   [3:0] add_ln1118_fu_824_p2;
wire   [3:0] add_ln727_fu_834_p2;
wire   [31:0] zext_ln201_fu_844_p1;
wire  signed [31:0] r_V_13_fu_857_p1;
wire   [47:0] lhs_8_fu_862_p3;
wire   [47:0] r_V_13_fu_857_p2;
wire   [47:0] ret_V_fu_870_p2;
wire   [3:0] trunc_ln1118_7_fu_893_p1;
wire   [3:0] add_ln1118_3_fu_897_p2;
wire   [3:0] add_ln727_1_fu_907_p2;
wire   [31:0] zext_ln201_1_fu_917_p1;
wire  signed [31:0] r_V_14_fu_930_p1;
wire   [47:0] lhs_10_fu_935_p3;
wire   [47:0] r_V_14_fu_930_p2;
wire   [47:0] ret_V_3_fu_943_p2;
wire   [0:0] icmp_ln184_1_fu_638_p2;
reg   [60:0] ap_NS_fsm;
reg    ap_condition_716;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 61'd1;
end

kalman_hw_update_sdiv_34ns_32s_32_38_1 #(
    .ID( 1 ),
    .NUM_STAGE( 38 ),
    .din0_WIDTH( 34 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sdiv_34ns_32s_32_38_1_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(34'd4294967296),
    .din1(hw_filter_innovation_covariance_data_V_q0),
    .ce(1'b1),
    .dout(grp_fu_647_p2)
);

kalman_hw_update_mul_32s_32s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_1_1_U31(
    .din0(hw_filter_innovation_covariance_data_V_q0),
    .din1(r_V_9_fu_694_p1),
    .dout(r_V_9_fu_694_p2)
);

kalman_hw_update_mul_32s_32s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_1_1_U32(
    .din0(hw_filter_inverse_innovation_covariance_data_V_q0),
    .din1(r_V_11_fu_743_p1),
    .dout(r_V_11_fu_743_p2)
);

kalman_hw_update_mul_32s_32s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_1_1_U33(
    .din0(hw_filter_innovation_covariance_data_V_q1),
    .din1(r_V_13_fu_857_p1),
    .dout(r_V_13_fu_857_p2)
);

kalman_hw_update_mul_32s_32s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_1_1_U34(
    .din0(hw_filter_inverse_innovation_covariance_data_V_q1),
    .din1(r_V_14_fu_930_p1),
    .dout(r_V_14_fu_930_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln46_fu_368_p2 == 1'd1))) begin
        i_reg_196 <= 31'd0;
    end else if (((icmp_ln48_fu_438_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_reg_196 <= add_ln46_reg_981;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln233_fu_787_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state56))) begin
        indvars_iv_reg_231 <= add_ln213_1_fu_798_p2;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln46_4_fu_400_p2 == 1'd1))) begin
        indvars_iv_reg_231 <= 32'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (((icmp_ln222_fu_548_p2 == 1'd0) & (icmp_ln217_reg_1061 == 1'd0) & (icmp_ln213_reg_1037 == 1'd1) & (cmp12_i_reg_994 == 1'd1) & (icmp_ln46_reg_966 == 1'd1)) | ((icmp_ln222_fu_548_p2 == 1'd0) & (grp_fu_348_p2 == 1'd0) & (icmp_ln213_reg_1037 == 1'd1) & (cmp12_i_reg_994 == 1'd1) & (icmp_ln46_reg_966 == 1'd1))))) begin
        j_11_reg_271 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        j_11_reg_271 <= add_ln184_reg_1082;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln184_fu_599_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        j_12_reg_282 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        j_12_reg_282 <= add_ln184_1_reg_1100;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state51) & (cmp12_i_reg_994 == 1'd1))) begin
        j_13_reg_293 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state53)) begin
        j_13_reg_293 <= add_ln193_reg_1129;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln193_fu_685_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state52))) begin
        j_14_reg_304 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state55)) begin
        j_14_reg_304 <= add_ln193_1_reg_1142;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state57) & (cmp12_i_reg_994 == 1'd1))) begin
        j_16_reg_326 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state59)) begin
        j_16_reg_326 <= add_ln201_reg_1189;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln201_fu_848_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state58))) begin
        j_17_reg_337 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state61)) begin
        j_17_reg_337 <= add_ln201_1_reg_1208;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln46_4_fu_400_p2 == 1'd0))) begin
        j_reg_208 <= 5'd0;
    end else if (((icmp_ln48_fu_438_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        j_reg_208 <= add_ln48_fu_410_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state60) & ((cmp12_i_reg_994 == 1'd0) | ((icmp_ln201_1_fu_921_p2 == 1'd1) | (icmp_ln235_reg_1174 == 1'd1))))) begin
        r1_reg_315 <= add_ln233_reg_1155;
    end else if (((1'b1 == ap_CS_fsm_state54) & ((icmp_ln193_1_fu_734_p2 == 1'd1) | (cmp12_i_reg_994 == 1'd0)))) begin
        r1_reg_315 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln233_fu_787_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state56))) begin
        r2_2_reg_219 <= add_ln213_reg_1041;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln46_4_fu_400_p2 == 1'd1))) begin
        r2_2_reg_219 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln217_fu_532_p2 == 1'd0))) begin
        r2_reg_262 <= r_fu_526_p2;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln217_reg_1061 == 1'd1) & (grp_fu_348_p2 == 1'd0) & (icmp_ln213_reg_1037 == 1'd1) & (icmp_ln46_reg_966 == 1'd1))) begin
        r2_reg_262 <= trunc_ln219_fu_543_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_348_p2 == 1'd1)) begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            r_04_in_reg_253 <= zext_ln200_1_reg_1032;
        end else if ((1'b1 == ap_condition_716)) begin
            r_04_in_reg_253 <= r_reg_1055;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_348_p2 == 1'd1)) begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            r_1_reg_243 <= zext_ln200_reg_1006;
        end else if ((1'b1 == ap_condition_716)) begin
            r_1_reg_243 <= add_ln217_fu_537_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln1498_reg_1046 == 1'd1))) begin
        add_ln184_1_reg_1100 <= add_ln184_1_fu_604_p2;
        hw_filter_inverse_innovation_covariance_data_V_addr_1_reg_1105 <= zext_ln186_1_fu_619_p1;
        hw_filter_inverse_innovation_covariance_data_V_addr_2_reg_1110 <= zext_ln187_1_fu_629_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln184_reg_1082 <= add_ln184_fu_565_p2;
        hw_filter_innovation_covariance_data_V_addr_2_reg_1087 <= zext_ln186_fu_580_p1;
        hw_filter_innovation_covariance_data_V_addr_3_reg_1092 <= zext_ln187_fu_590_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state54) & (cmp12_i_reg_994 == 1'd1))) begin
        add_ln193_1_reg_1142 <= add_ln193_1_fu_710_p2;
        hw_filter_inverse_innovation_covariance_data_V_addr_3_reg_1147 <= zext_ln1116_3_fu_725_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state52)) begin
        add_ln193_reg_1129 <= add_ln193_fu_661_p2;
        hw_filter_innovation_covariance_data_V_addr_4_reg_1134 <= zext_ln1116_fu_676_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln235_reg_1174 == 1'd0) & (1'b1 == ap_CS_fsm_state60) & (cmp12_i_reg_994 == 1'd1))) begin
        add_ln201_1_reg_1208 <= add_ln201_1_fu_887_p2;
        hw_filter_inverse_innovation_covariance_data_V_addr_5_reg_1218 <= zext_ln727_1_fu_912_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state58)) begin
        add_ln201_reg_1189 <= add_ln201_fu_814_p2;
        hw_filter_innovation_covariance_data_V_addr_7_reg_1199 <= zext_ln727_fu_839_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln213_reg_1041 <= add_ln213_fu_498_p2;
        hw_filter_innovation_covariance_data_V_addr_reg_1027 <= zext_ln1498_fu_484_p1;
        icmp_ln213_reg_1037 <= icmp_ln213_fu_493_p2;
        tmp_16_cast_reg_1017[3 : 2] <= tmp_16_cast_fu_470_p3[3 : 2];
        trunc_ln1498_reg_1011 <= trunc_ln1498_fu_462_p1;
        zext_ln200_1_reg_1032[30 : 0] <= zext_ln200_1_fu_489_p1[30 : 0];
        zext_ln200_reg_1006[31 : 0] <= zext_ln200_fu_458_p1[31 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        add_ln233_reg_1155 <= add_ln233_fu_759_p2;
        tmp_20_cast_reg_1160[3 : 2] <= tmp_20_cast_fu_769_p3[3 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln46_reg_981 <= add_ln46_fu_382_p2;
        tmp_cast_reg_986[3 : 2] <= tmp_cast_fu_392_p3[3 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln46_4_fu_400_p2 == 1'd1))) begin
        cmp12_i_reg_994 <= cmp12_i_fu_405_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        icmp_ln1498_reg_1046 <= grp_fu_348_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        icmp_ln217_reg_1061 <= icmp_ln217_fu_532_p2;
        r_reg_1055 <= r_fu_526_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln233_fu_787_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state56))) begin
        icmp_ln235_reg_1174 <= icmp_ln235_fu_792_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln46_reg_966 <= icmp_ln46_fu_368_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        sext_ln193_reg_1123 <= sext_ln193_fu_657_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        sext_ln201_reg_1183 <= sext_ln201_fu_810_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (((icmp_ln222_fu_548_p2 == 1'd0) & (icmp_ln217_reg_1061 == 1'd0) & (icmp_ln213_reg_1037 == 1'd1) & (icmp_ln46_reg_966 == 1'd1)) | ((icmp_ln222_fu_548_p2 == 1'd0) & (grp_fu_348_p2 == 1'd0) & (icmp_ln213_reg_1037 == 1'd1) & (icmp_ln46_reg_966 == 1'd1))))) begin
        tmp_19_cast_reg_1076[3 : 2] <= tmp_19_cast_fu_557_p3[3 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln46_fu_368_p2 == 1'd1))) begin
        trunc_ln46_reg_975 <= trunc_ln46_fu_378_p1;
        zext_ln46_reg_970[31 : 0] <= zext_ln46_fu_374_p1[31 : 0];
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state7) & ((icmp_ln46_reg_966 == 1'd0) | ((icmp_ln213_reg_1037 == 1'd0) | (((icmp_ln222_fu_548_p2 == 1'd1) & (icmp_ln217_reg_1061 == 1'd0)) | ((icmp_ln222_fu_548_p2 == 1'd1) & (grp_fu_348_p2 == 1'd0)))))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln217_reg_1061 == 1'd1) & (grp_fu_348_p2 == 1'd0) & (icmp_ln213_reg_1037 == 1'd1) & (icmp_ln46_reg_966 == 1'd1))) begin
        ap_phi_mux_r2_phi_fu_265_p4 = trunc_ln219_fu_543_p1;
    end else begin
        ap_phi_mux_r2_phi_fu_265_p4 = r2_reg_262;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & ((icmp_ln46_reg_966 == 1'd0) | ((icmp_ln213_reg_1037 == 1'd0) | (((icmp_ln222_fu_548_p2 == 1'd1) & (icmp_ln217_reg_1061 == 1'd0)) | ((icmp_ln222_fu_548_p2 == 1'd1) & (grp_fu_348_p2 == 1'd0))))))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state58)) begin
        hw_filter_innovation_covariance_data_V_address0 = zext_ln727_fu_839_p1;
    end else if ((1'b1 == ap_CS_fsm_state56)) begin
        hw_filter_innovation_covariance_data_V_address0 = zext_ln703_fu_782_p1;
    end else if ((1'b1 == ap_CS_fsm_state53)) begin
        hw_filter_innovation_covariance_data_V_address0 = hw_filter_innovation_covariance_data_V_addr_4_reg_1134;
    end else if ((1'b1 == ap_CS_fsm_state52)) begin
        hw_filter_innovation_covariance_data_V_address0 = zext_ln1116_fu_676_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        hw_filter_innovation_covariance_data_V_address0 = hw_filter_innovation_covariance_data_V_addr_reg_1027;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        hw_filter_innovation_covariance_data_V_address0 = hw_filter_innovation_covariance_data_V_addr_3_reg_1092;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        hw_filter_innovation_covariance_data_V_address0 = hw_filter_innovation_covariance_data_V_addr_2_reg_1087;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        hw_filter_innovation_covariance_data_V_address0 = zext_ln187_fu_590_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        hw_filter_innovation_covariance_data_V_address0 = zext_ln1499_fu_521_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        hw_filter_innovation_covariance_data_V_address0 = zext_ln1498_fu_484_p1;
    end else begin
        hw_filter_innovation_covariance_data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state59)) begin
        hw_filter_innovation_covariance_data_V_address1 = hw_filter_innovation_covariance_data_V_addr_7_reg_1199;
    end else if ((1'b1 == ap_CS_fsm_state58)) begin
        hw_filter_innovation_covariance_data_V_address1 = zext_ln1118_fu_829_p1;
    end else begin
        hw_filter_innovation_covariance_data_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state58) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state52) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        hw_filter_innovation_covariance_data_V_ce0 = 1'b1;
    end else begin
        hw_filter_innovation_covariance_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state59) | (1'b1 == ap_CS_fsm_state58))) begin
        hw_filter_innovation_covariance_data_V_ce1 = 1'b1;
    end else begin
        hw_filter_innovation_covariance_data_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state53)) begin
        hw_filter_innovation_covariance_data_V_d0 = {{r_V_9_fu_694_p2[47:16]}};
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        hw_filter_innovation_covariance_data_V_d0 = hw_filter_innovation_covariance_data_V_q0;
    end else begin
        hw_filter_innovation_covariance_data_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state10))) begin
        hw_filter_innovation_covariance_data_V_we0 = 1'b1;
    end else begin
        hw_filter_innovation_covariance_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state59)) begin
        hw_filter_innovation_covariance_data_V_we1 = 1'b1;
    end else begin
        hw_filter_innovation_covariance_data_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        hw_filter_inverse_innovation_covariance_cols_ap_vld = 1'b1;
    end else begin
        hw_filter_inverse_innovation_covariance_cols_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state60)) begin
        hw_filter_inverse_innovation_covariance_data_V_address0 = zext_ln727_1_fu_912_p1;
    end else if ((1'b1 == ap_CS_fsm_state55)) begin
        hw_filter_inverse_innovation_covariance_data_V_address0 = hw_filter_inverse_innovation_covariance_data_V_addr_3_reg_1147;
    end else if ((1'b1 == ap_CS_fsm_state54)) begin
        hw_filter_inverse_innovation_covariance_data_V_address0 = zext_ln1116_3_fu_725_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        hw_filter_inverse_innovation_covariance_data_V_address0 = hw_filter_inverse_innovation_covariance_data_V_addr_2_reg_1110;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        hw_filter_inverse_innovation_covariance_data_V_address0 = hw_filter_inverse_innovation_covariance_data_V_addr_1_reg_1105;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        hw_filter_inverse_innovation_covariance_data_V_address0 = zext_ln187_1_fu_629_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        hw_filter_inverse_innovation_covariance_data_V_address0 = zext_ln50_fu_425_p1;
    end else begin
        hw_filter_inverse_innovation_covariance_data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state61)) begin
        hw_filter_inverse_innovation_covariance_data_V_address1 = hw_filter_inverse_innovation_covariance_data_V_addr_5_reg_1218;
    end else if ((1'b1 == ap_CS_fsm_state60)) begin
        hw_filter_inverse_innovation_covariance_data_V_address1 = zext_ln1118_3_fu_902_p1;
    end else begin
        hw_filter_inverse_innovation_covariance_data_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state60) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state3))) begin
        hw_filter_inverse_innovation_covariance_data_V_ce0 = 1'b1;
    end else begin
        hw_filter_inverse_innovation_covariance_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state61) | (1'b1 == ap_CS_fsm_state60))) begin
        hw_filter_inverse_innovation_covariance_data_V_ce1 = 1'b1;
    end else begin
        hw_filter_inverse_innovation_covariance_data_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        hw_filter_inverse_innovation_covariance_data_V_d0 = {{r_V_11_fu_743_p2[47:16]}};
    end else if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state13))) begin
        hw_filter_inverse_innovation_covariance_data_V_d0 = hw_filter_inverse_innovation_covariance_data_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        hw_filter_inverse_innovation_covariance_data_V_d0 = select_ln50_fu_449_p3;
    end else begin
        hw_filter_inverse_innovation_covariance_data_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state13) | ((icmp_ln48_fu_438_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        hw_filter_inverse_innovation_covariance_data_V_we0 = 1'b1;
    end else begin
        hw_filter_inverse_innovation_covariance_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state61)) begin
        hw_filter_inverse_innovation_covariance_data_V_we1 = 1'b1;
    end else begin
        hw_filter_inverse_innovation_covariance_data_V_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln46_fu_368_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln46_fu_368_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln46_4_fu_400_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln48_fu_438_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln213_fu_493_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_fu_348_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & ((icmp_ln46_reg_966 == 1'd0) | ((icmp_ln213_reg_1037 == 1'd0) | (((icmp_ln222_fu_548_p2 == 1'd1) & (icmp_ln217_reg_1061 == 1'd0)) | ((icmp_ln222_fu_548_p2 == 1'd1) & (grp_fu_348_p2 == 1'd0))))))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b1 == ap_CS_fsm_state7) & (((icmp_ln222_fu_548_p2 == 1'd0) & (icmp_ln217_reg_1061 == 1'd0) & (icmp_ln213_reg_1037 == 1'd1) & (cmp12_i_reg_994 == 1'd1) & (icmp_ln46_reg_966 == 1'd1)) | ((icmp_ln222_fu_548_p2 == 1'd0) & (grp_fu_348_p2 == 1'd0) & (icmp_ln213_reg_1037 == 1'd1) & (cmp12_i_reg_994 == 1'd1) & (icmp_ln46_reg_966 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if (((1'b1 == ap_CS_fsm_state7) & (((icmp_ln222_fu_548_p2 == 1'd0) & (icmp_ln217_reg_1061 == 1'd0) & (icmp_ln213_reg_1037 == 1'd1) & (cmp12_i_reg_994 == 1'd0) & (icmp_ln46_reg_966 == 1'd1)) | ((icmp_ln222_fu_548_p2 == 1'd0) & (grp_fu_348_p2 == 1'd0) & (icmp_ln213_reg_1037 == 1'd1) & (cmp12_i_reg_994 == 1'd0) & (icmp_ln46_reg_966 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state54;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((icmp_ln184_fu_599_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & ((icmp_ln184_1_fu_638_p2 == 1'd1) | (icmp_ln1498_reg_1046 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            if (((1'b1 == ap_CS_fsm_state51) & (cmp12_i_reg_994 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state52;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state54;
            end
        end
        ap_ST_fsm_state52 : begin
            if (((icmp_ln193_fu_685_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state52))) begin
                ap_NS_fsm = ap_ST_fsm_state54;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state53;
            end
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state54 : begin
            if (((1'b1 == ap_CS_fsm_state54) & ((icmp_ln193_1_fu_734_p2 == 1'd1) | (cmp12_i_reg_994 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state56;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state55;
            end
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state56 : begin
            if (((icmp_ln233_fu_787_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state56))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if (((icmp_ln233_fu_787_p2 == 1'd0) & (icmp_ln235_fu_792_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state56))) begin
                ap_NS_fsm = ap_ST_fsm_state60;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state57;
            end
        end
        ap_ST_fsm_state57 : begin
            if (((1'b1 == ap_CS_fsm_state57) & (cmp12_i_reg_994 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state58;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state60;
            end
        end
        ap_ST_fsm_state58 : begin
            if (((icmp_ln201_fu_848_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state58))) begin
                ap_NS_fsm = ap_ST_fsm_state60;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state59;
            end
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state60 : begin
            if (((1'b1 == ap_CS_fsm_state60) & ((cmp12_i_reg_994 == 1'd0) | ((icmp_ln201_1_fu_921_p2 == 1'd1) | (icmp_ln235_reg_1174 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state56;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state61;
            end
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1116_3_fu_720_p2 = (tmp_16_cast_reg_1017 + trunc_ln1116_4_fu_716_p1);

assign add_ln1116_fu_671_p2 = (tmp_16_cast_reg_1017 + trunc_ln1116_fu_667_p1);

assign add_ln1118_3_fu_897_p2 = (tmp_16_cast_reg_1017 + trunc_ln1118_7_fu_893_p1);

assign add_ln1118_fu_824_p2 = (tmp_16_cast_reg_1017 + trunc_ln1118_fu_820_p1);

assign add_ln1498_fu_478_p2 = (tmp_16_cast_fu_470_p3 + trunc_ln1498_fu_462_p1);

assign add_ln1499_fu_516_p2 = (tmp_18_cast_fu_508_p3 + trunc_ln1498_reg_1011);

assign add_ln184_1_fu_604_p2 = (j_12_reg_282 + 5'd1);

assign add_ln184_fu_565_p2 = (j_11_reg_271 + 5'd1);

assign add_ln186_1_fu_614_p2 = (tmp_16_cast_reg_1017 + trunc_ln186_1_fu_610_p1);

assign add_ln186_fu_575_p2 = (tmp_16_cast_reg_1017 + trunc_ln186_fu_571_p1);

assign add_ln187_1_fu_624_p2 = (tmp_19_cast_reg_1076 + trunc_ln186_1_fu_610_p1);

assign add_ln187_fu_585_p2 = (tmp_19_cast_reg_1076 + trunc_ln186_fu_571_p1);

assign add_ln193_1_fu_710_p2 = (j_14_reg_304 + 5'd1);

assign add_ln193_fu_661_p2 = (j_13_reg_293 + 5'd1);

assign add_ln201_1_fu_887_p2 = (j_17_reg_337 + 5'd1);

assign add_ln201_fu_814_p2 = (j_16_reg_326 + 5'd1);

assign add_ln213_1_fu_798_p2 = (indvars_iv_reg_231 + 32'd1);

assign add_ln213_fu_498_p2 = (r2_2_reg_219 + 31'd1);

assign add_ln217_fu_537_p2 = (r_1_reg_243 + 64'd1);

assign add_ln233_fu_759_p2 = (r1_reg_315 + 31'd1);

assign add_ln46_fu_382_p2 = (i_reg_196 + 31'd1);

assign add_ln48_fu_410_p2 = (j_reg_208 + 5'd1);

assign add_ln50_fu_420_p2 = (tmp_cast_reg_986 + trunc_ln50_6_fu_416_p1);

assign add_ln703_fu_777_p2 = (tmp_20_cast_fu_769_p3 + trunc_ln1498_reg_1011);

assign add_ln727_1_fu_907_p2 = (tmp_20_cast_reg_1160 + trunc_ln1118_7_fu_893_p1);

assign add_ln727_fu_834_p2 = (tmp_20_cast_reg_1160 + trunc_ln1118_fu_820_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state52 = ap_CS_fsm[32'd51];

assign ap_CS_fsm_state53 = ap_CS_fsm[32'd52];

assign ap_CS_fsm_state54 = ap_CS_fsm[32'd53];

assign ap_CS_fsm_state55 = ap_CS_fsm[32'd54];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_state58 = ap_CS_fsm[32'd57];

assign ap_CS_fsm_state59 = ap_CS_fsm[32'd58];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state60 = ap_CS_fsm[32'd59];

assign ap_CS_fsm_state61 = ap_CS_fsm[32'd60];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_condition_716 = ((1'b1 == ap_CS_fsm_state7) & (icmp_ln217_reg_1061 == 1'd1) & (icmp_ln213_reg_1037 == 1'd1) & (icmp_ln46_reg_966 == 1'd1));
end

assign cmp12_i_fu_405_p2 = (($signed(hw_filter_innovation_covariance_cols) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign grp_fu_348_p2 = ((hw_filter_innovation_covariance_data_V_q0 == 32'd0) ? 1'b1 : 1'b0);

assign hw_filter_innovation_covariance_data_V_d1 = {{ret_V_fu_870_p2[47:16]}};

assign hw_filter_inverse_innovation_covariance_cols = hw_filter_innovation_covariance_cols;

assign hw_filter_inverse_innovation_covariance_data_V_d1 = {{ret_V_3_fu_943_p2[47:16]}};

assign icmp_ln184_1_fu_638_p2 = ((zext_ln184_1_fu_634_p1 == hw_filter_innovation_covariance_cols) ? 1'b1 : 1'b0);

assign icmp_ln184_fu_599_p2 = ((zext_ln184_fu_595_p1 == hw_filter_innovation_covariance_cols) ? 1'b1 : 1'b0);

assign icmp_ln193_1_fu_734_p2 = ((zext_ln193_1_fu_730_p1 == hw_filter_innovation_covariance_cols) ? 1'b1 : 1'b0);

assign icmp_ln193_fu_685_p2 = ((zext_ln193_fu_681_p1 == hw_filter_innovation_covariance_cols) ? 1'b1 : 1'b0);

assign icmp_ln201_1_fu_921_p2 = ((zext_ln201_1_fu_917_p1 == hw_filter_innovation_covariance_cols) ? 1'b1 : 1'b0);

assign icmp_ln201_fu_848_p2 = ((zext_ln201_fu_844_p1 == hw_filter_innovation_covariance_cols) ? 1'b1 : 1'b0);

assign icmp_ln213_fu_493_p2 = (($signed(zext_ln200_1_fu_489_p1) < $signed(hw_filter_innovation_covariance_rows)) ? 1'b1 : 1'b0);

assign icmp_ln217_fu_532_p2 = (($signed(r_1_reg_243) < $signed(zext_ln46_reg_970)) ? 1'b1 : 1'b0);

assign icmp_ln222_fu_548_p2 = ((ap_phi_mux_r2_phi_fu_265_p4 == hw_filter_innovation_covariance_rows) ? 1'b1 : 1'b0);

assign icmp_ln233_fu_787_p2 = ((r1_reg_315 == trunc_ln46_reg_975) ? 1'b1 : 1'b0);

assign icmp_ln235_fu_792_p2 = ((r2_2_reg_219 == r1_reg_315) ? 1'b1 : 1'b0);

assign icmp_ln46_4_fu_400_p2 = ((i_reg_196 == trunc_ln46_reg_975) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_368_p2 = (($signed(hw_filter_innovation_covariance_rows) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln48_fu_438_p2 = ((zext_ln48_4_fu_434_p1 == hw_filter_innovation_covariance_cols) ? 1'b1 : 1'b0);

assign icmp_ln50_fu_443_p2 = ((i_reg_196 == zext_ln48_fu_430_p1) ? 1'b1 : 1'b0);

assign lhs_10_fu_935_p3 = {{hw_filter_inverse_innovation_covariance_data_V_q0}, {16'd0}};

assign lhs_8_fu_862_p3 = {{hw_filter_innovation_covariance_data_V_q0}, {16'd0}};

assign r_V_11_fu_743_p1 = sext_ln193_reg_1123;

assign r_V_13_fu_857_p1 = sext_ln201_reg_1183;

assign r_V_14_fu_930_p1 = sext_ln201_reg_1183;

assign r_V_9_fu_694_p1 = sext_ln193_reg_1123;

assign r_fu_526_p2 = (r_04_in_reg_253 + 32'd1);

assign ret_V_3_fu_943_p2 = (lhs_10_fu_935_p3 + r_V_14_fu_930_p2);

assign ret_V_fu_870_p2 = (lhs_8_fu_862_p3 + r_V_13_fu_857_p2);

assign scalar_V_2_fu_804_p2 = (32'd0 - hw_filter_innovation_covariance_data_V_q0);

assign scalar_V_fu_653_p1 = grp_fu_647_p2[31:0];

assign select_ln50_fu_449_p3 = ((icmp_ln50_fu_443_p2[0:0] == 1'b1) ? 32'd65536 : 32'd0);

assign sext_ln193_fu_657_p1 = $signed(scalar_V_fu_653_p1);

assign sext_ln201_fu_810_p1 = $signed(scalar_V_2_fu_804_p2);

assign tmp_16_cast_fu_470_p3 = {{trunc_ln1498_1_fu_466_p1}, {2'd0}};

assign tmp_18_cast_fu_508_p3 = {{trunc_ln1499_fu_504_p1}, {2'd0}};

assign tmp_19_cast_fu_557_p3 = {{trunc_ln187_fu_553_p1}, {2'd0}};

assign tmp_20_cast_fu_769_p3 = {{trunc_ln703_fu_765_p1}, {2'd0}};

assign tmp_cast_fu_392_p3 = {{trunc_ln50_fu_388_p1}, {2'd0}};

assign trunc_ln1116_4_fu_716_p1 = j_14_reg_304[3:0];

assign trunc_ln1116_fu_667_p1 = j_13_reg_293[3:0];

assign trunc_ln1118_7_fu_893_p1 = j_17_reg_337[3:0];

assign trunc_ln1118_fu_820_p1 = j_16_reg_326[3:0];

assign trunc_ln1498_1_fu_466_p1 = r2_2_reg_219[1:0];

assign trunc_ln1498_fu_462_p1 = r2_2_reg_219[3:0];

assign trunc_ln1499_fu_504_p1 = r_1_reg_243[1:0];

assign trunc_ln186_1_fu_610_p1 = j_12_reg_282[3:0];

assign trunc_ln186_fu_571_p1 = j_11_reg_271[3:0];

assign trunc_ln187_fu_553_p1 = ap_phi_mux_r2_phi_fu_265_p4[1:0];

assign trunc_ln219_fu_543_p1 = r_1_reg_243[31:0];

assign trunc_ln46_fu_378_p1 = hw_filter_innovation_covariance_rows[30:0];

assign trunc_ln50_6_fu_416_p1 = j_reg_208[3:0];

assign trunc_ln50_fu_388_p1 = i_reg_196[1:0];

assign trunc_ln703_fu_765_p1 = r1_reg_315[1:0];

assign zext_ln1116_3_fu_725_p1 = add_ln1116_3_fu_720_p2;

assign zext_ln1116_fu_676_p1 = add_ln1116_fu_671_p2;

assign zext_ln1118_3_fu_902_p1 = add_ln1118_3_fu_897_p2;

assign zext_ln1118_fu_829_p1 = add_ln1118_fu_824_p2;

assign zext_ln1498_fu_484_p1 = add_ln1498_fu_478_p2;

assign zext_ln1499_fu_521_p1 = add_ln1499_fu_516_p2;

assign zext_ln184_1_fu_634_p1 = j_12_reg_282;

assign zext_ln184_fu_595_p1 = j_11_reg_271;

assign zext_ln186_1_fu_619_p1 = add_ln186_1_fu_614_p2;

assign zext_ln186_fu_580_p1 = add_ln186_fu_575_p2;

assign zext_ln187_1_fu_629_p1 = add_ln187_1_fu_624_p2;

assign zext_ln187_fu_590_p1 = add_ln187_fu_585_p2;

assign zext_ln193_1_fu_730_p1 = j_14_reg_304;

assign zext_ln193_fu_681_p1 = j_13_reg_293;

assign zext_ln200_1_fu_489_p1 = r2_2_reg_219;

assign zext_ln200_fu_458_p1 = indvars_iv_reg_231;

assign zext_ln201_1_fu_917_p1 = j_17_reg_337;

assign zext_ln201_fu_844_p1 = j_16_reg_326;

assign zext_ln46_fu_374_p1 = hw_filter_innovation_covariance_rows;

assign zext_ln48_4_fu_434_p1 = j_reg_208;

assign zext_ln48_fu_430_p1 = j_reg_208;

assign zext_ln50_fu_425_p1 = add_ln50_fu_420_p2;

assign zext_ln703_fu_782_p1 = add_ln703_fu_777_p2;

assign zext_ln727_1_fu_912_p1 = add_ln727_1_fu_907_p2;

assign zext_ln727_fu_839_p1 = add_ln727_fu_834_p2;

always @ (posedge ap_clk) begin
    zext_ln46_reg_970[63:32] <= 32'b00000000000000000000000000000000;
    tmp_cast_reg_986[1:0] <= 2'b00;
    zext_ln200_reg_1006[63:32] <= 32'b00000000000000000000000000000000;
    tmp_16_cast_reg_1017[1:0] <= 2'b00;
    zext_ln200_1_reg_1032[31] <= 1'b0;
    tmp_19_cast_reg_1076[1:0] <= 2'b00;
    tmp_20_cast_reg_1160[1:0] <= 2'b00;
end

endmodule //kalman_hw_update_destructive_invert_matrix
