// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module kalman_hw_update_multiply_matrix (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        a_data_address0,
        a_data_ce0,
        a_data_q0,
        p_read2,
        b_data_address0,
        b_data_ce0,
        b_data_q0,
        c_data_address0,
        c_data_ce0,
        c_data_we0,
        c_data_d0,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] p_read;
input  [31:0] p_read1;
output  [3:0] a_data_address0;
output   a_data_ce0;
input  [31:0] a_data_q0;
input  [31:0] p_read2;
output  [3:0] b_data_address0;
output   b_data_ce0;
input  [31:0] b_data_q0;
output  [3:0] c_data_address0;
output   c_data_ce0;
output   c_data_we0;
output  [31:0] c_data_d0;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg a_data_ce0;
reg b_data_ce0;
reg[3:0] c_data_address0;
reg c_data_ce0;
reg c_data_we0;
reg[31:0] c_data_d0;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] cmp91_fu_162_p2;
reg   [0:0] cmp91_reg_336;
wire   [31:0] add_ln118_fu_168_p2;
reg   [31:0] add_ln118_reg_340;
wire    ap_CS_fsm_state2;
wire   [3:0] tmp_cast_fu_178_p3;
reg   [3:0] tmp_cast_reg_345;
wire   [4:0] add_ln120_fu_201_p2;
reg   [4:0] add_ln120_reg_354;
wire    ap_CS_fsm_state3;
wire   [3:0] trunc_ln122_fu_207_p1;
reg   [3:0] trunc_ln122_reg_359;
reg   [3:0] c_data_addr_reg_364;
wire   [30:0] add_ln123_fu_230_p2;
reg   [30:0] add_ln123_reg_372;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [31:0] i_reg_116;
wire   [0:0] icmp_ln120_fu_225_p2;
reg   [4:0] j_reg_127;
wire   [0:0] icmp_ln118_fu_186_p2;
wire   [0:0] icmp_ln123_fu_276_p2;
reg   [30:0] k_reg_138;
reg   [31:0] lhs_reg_149;
wire   [63:0] zext_ln122_fu_216_p1;
wire   [63:0] zext_ln1116_fu_245_p1;
wire   [63:0] zext_ln1118_fu_267_p1;
wire   [1:0] trunc_ln1116_fu_174_p1;
wire   [3:0] add_ln122_fu_211_p2;
wire   [31:0] zext_ln120_fu_221_p1;
wire   [3:0] trunc_ln1116_2_fu_236_p1;
wire   [3:0] add_ln1116_fu_240_p2;
wire   [1:0] trunc_ln1118_fu_250_p1;
wire   [3:0] tmp_7_cast_fu_254_p3;
wire   [3:0] add_ln1118_fu_262_p2;
wire   [31:0] zext_ln123_fu_272_p1;
wire   [47:0] lhs_6_fu_295_p3;
wire   [47:0] r_V_6_fu_289_p2;
wire   [47:0] ret_V_fu_303_p2;
reg   [4:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
end

kalman_hw_update_mul_32s_32s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_1_1_U23(
    .din0(b_data_q0),
    .din1(a_data_q0),
    .dout(r_V_6_fu_289_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_reg_116 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln120_fu_225_p2 == 1'd1))) begin
        i_reg_116 <= add_ln118_reg_340;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & ((cmp91_reg_336 == 1'd0) | (icmp_ln123_fu_276_p2 == 1'd1)))) begin
        j_reg_127 <= add_ln120_reg_354;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln118_fu_186_p2 == 1'd0))) begin
        j_reg_127 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp91_reg_336 == 1'd1) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln120_fu_225_p2 == 1'd0))) begin
        k_reg_138 <= 31'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        k_reg_138 <= add_ln123_reg_372;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp91_reg_336 == 1'd1) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln120_fu_225_p2 == 1'd0))) begin
        lhs_reg_149 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        lhs_reg_149 <= {{ret_V_fu_303_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln118_reg_340 <= add_ln118_fu_168_p2;
        tmp_cast_reg_345[3 : 2] <= tmp_cast_fu_178_p3[3 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln120_reg_354 <= add_ln120_fu_201_p2;
        c_data_addr_reg_364 <= zext_ln122_fu_216_p1;
        trunc_ln122_reg_359 <= trunc_ln122_fu_207_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp91_reg_336 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        add_ln123_reg_372 <= add_ln123_fu_230_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        cmp91_reg_336 <= cmp91_fu_162_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        a_data_ce0 = 1'b1;
    end else begin
        a_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (icmp_ln118_fu_186_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln118_fu_186_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        b_data_ce0 = 1'b1;
    end else begin
        b_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        c_data_address0 = c_data_addr_reg_364;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        c_data_address0 = zext_ln122_fu_216_p1;
    end else begin
        c_data_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        c_data_ce0 = 1'b1;
    end else begin
        c_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        c_data_d0 = lhs_reg_149;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        c_data_d0 = 32'd0;
    end else begin
        c_data_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((cmp91_reg_336 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln123_fu_276_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln120_fu_225_p2 == 1'd0)))) begin
        c_data_we0 = 1'b1;
    end else begin
        c_data_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln118_fu_186_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln120_fu_225_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & ((cmp91_reg_336 == 1'd0) | (icmp_ln123_fu_276_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_data_address0 = zext_ln1116_fu_245_p1;

assign add_ln1116_fu_240_p2 = (tmp_cast_reg_345 + trunc_ln1116_2_fu_236_p1);

assign add_ln1118_fu_262_p2 = (tmp_7_cast_fu_254_p3 + trunc_ln122_reg_359);

assign add_ln118_fu_168_p2 = (i_reg_116 + 32'd1);

assign add_ln120_fu_201_p2 = (j_reg_127 + 5'd1);

assign add_ln122_fu_211_p2 = (tmp_cast_reg_345 + trunc_ln122_fu_207_p1);

assign add_ln123_fu_230_p2 = (k_reg_138 + 31'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_return_0 = p_read;

assign ap_return_1 = p_read2;

assign b_data_address0 = zext_ln1118_fu_267_p1;

assign cmp91_fu_162_p2 = (($signed(p_read1) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln118_fu_186_p2 = ((i_reg_116 == p_read) ? 1'b1 : 1'b0);

assign icmp_ln120_fu_225_p2 = ((zext_ln120_fu_221_p1 == p_read2) ? 1'b1 : 1'b0);

assign icmp_ln123_fu_276_p2 = ((zext_ln123_fu_272_p1 == p_read1) ? 1'b1 : 1'b0);

assign lhs_6_fu_295_p3 = {{lhs_reg_149}, {16'd0}};

assign ret_V_fu_303_p2 = (lhs_6_fu_295_p3 + r_V_6_fu_289_p2);

assign tmp_7_cast_fu_254_p3 = {{trunc_ln1118_fu_250_p1}, {2'd0}};

assign tmp_cast_fu_178_p3 = {{trunc_ln1116_fu_174_p1}, {2'd0}};

assign trunc_ln1116_2_fu_236_p1 = k_reg_138[3:0];

assign trunc_ln1116_fu_174_p1 = i_reg_116[1:0];

assign trunc_ln1118_fu_250_p1 = k_reg_138[1:0];

assign trunc_ln122_fu_207_p1 = j_reg_127[3:0];

assign zext_ln1116_fu_245_p1 = add_ln1116_fu_240_p2;

assign zext_ln1118_fu_267_p1 = add_ln1118_fu_262_p2;

assign zext_ln120_fu_221_p1 = j_reg_127;

assign zext_ln122_fu_216_p1 = add_ln122_fu_211_p2;

assign zext_ln123_fu_272_p1 = k_reg_138;

always @ (posedge ap_clk) begin
    tmp_cast_reg_345[1:0] <= 2'b00;
end

endmodule //kalman_hw_update_multiply_matrix
