-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity kalman_hw_update_multiply_matrix is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
    a_data_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    a_data_ce0 : OUT STD_LOGIC;
    a_data_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_data_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    b_data_ce0 : OUT STD_LOGIC;
    b_data_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    c_data_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    c_data_ce0 : OUT STD_LOGIC;
    c_data_we0 : OUT STD_LOGIC;
    c_data_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of kalman_hw_update_multiply_matrix is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal cmp91_fu_162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp91_reg_336 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln118_fu_168_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln118_reg_340 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_cast_fu_178_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_cast_reg_345 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln120_fu_201_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln120_reg_354 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal trunc_ln122_fu_207_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln122_reg_359 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_data_addr_reg_364 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln123_fu_230_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln123_reg_372 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal i_reg_116 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln120_fu_225_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_reg_127 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln118_fu_186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln123_fu_276_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal k_reg_138 : STD_LOGIC_VECTOR (30 downto 0);
    signal lhs_reg_149 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln122_fu_216_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1116_fu_245_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1118_fu_267_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln1116_fu_174_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln122_fu_211_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln120_fu_221_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1116_2_fu_236_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln1116_fu_240_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln1118_fu_250_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_7_cast_fu_254_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln1118_fu_262_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln123_fu_272_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lhs_6_fu_295_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal r_V_6_fu_289_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal ret_V_fu_303_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component kalman_hw_update_mul_32s_32s_48_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;



begin
    mul_32s_32s_48_1_1_U23 : component kalman_hw_update_mul_32s_32s_48_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        din0 => b_data_q0,
        din1 => a_data_q0,
        dout => r_V_6_fu_289_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_reg_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_reg_116 <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln120_fu_225_p2 = ap_const_lv1_1))) then 
                i_reg_116 <= add_ln118_reg_340;
            end if; 
        end if;
    end process;

    j_reg_127_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and ((cmp91_reg_336 = ap_const_lv1_0) or (icmp_ln123_fu_276_p2 = ap_const_lv1_1)))) then 
                j_reg_127 <= add_ln120_reg_354;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln118_fu_186_p2 = ap_const_lv1_0))) then 
                j_reg_127 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    k_reg_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((cmp91_reg_336 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln120_fu_225_p2 = ap_const_lv1_0))) then 
                k_reg_138 <= ap_const_lv31_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                k_reg_138 <= add_ln123_reg_372;
            end if; 
        end if;
    end process;

    lhs_reg_149_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((cmp91_reg_336 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln120_fu_225_p2 = ap_const_lv1_0))) then 
                lhs_reg_149 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                lhs_reg_149 <= ret_V_fu_303_p2(47 downto 16);
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln118_reg_340 <= add_ln118_fu_168_p2;
                    tmp_cast_reg_345(3 downto 2) <= tmp_cast_fu_178_p3(3 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln120_reg_354 <= add_ln120_fu_201_p2;
                c_data_addr_reg_364 <= zext_ln122_fu_216_p1(4 - 1 downto 0);
                trunc_ln122_reg_359 <= trunc_ln122_fu_207_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((cmp91_reg_336 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                add_ln123_reg_372 <= add_ln123_fu_230_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                cmp91_reg_336 <= cmp91_fu_162_p2;
            end if;
        end if;
    end process;
    tmp_cast_reg_345(1 downto 0) <= "00";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, cmp91_reg_336, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, icmp_ln120_fu_225_p2, icmp_ln118_fu_186_p2, icmp_ln123_fu_276_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln118_fu_186_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln120_fu_225_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and ((cmp91_reg_336 = ap_const_lv1_0) or (icmp_ln123_fu_276_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    a_data_address0 <= zext_ln1116_fu_245_p1(4 - 1 downto 0);

    a_data_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            a_data_ce0 <= ap_const_logic_1;
        else 
            a_data_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln1116_fu_240_p2 <= std_logic_vector(unsigned(tmp_cast_reg_345) + unsigned(trunc_ln1116_2_fu_236_p1));
    add_ln1118_fu_262_p2 <= std_logic_vector(unsigned(tmp_7_cast_fu_254_p3) + unsigned(trunc_ln122_reg_359));
    add_ln118_fu_168_p2 <= std_logic_vector(unsigned(i_reg_116) + unsigned(ap_const_lv32_1));
    add_ln120_fu_201_p2 <= std_logic_vector(unsigned(j_reg_127) + unsigned(ap_const_lv5_1));
    add_ln122_fu_211_p2 <= std_logic_vector(unsigned(tmp_cast_reg_345) + unsigned(trunc_ln122_fu_207_p1));
    add_ln123_fu_230_p2 <= std_logic_vector(unsigned(k_reg_138) + unsigned(ap_const_lv31_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln118_fu_186_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln118_fu_186_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln118_fu_186_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln118_fu_186_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= p_read;
    ap_return_1 <= p_read2;
    b_data_address0 <= zext_ln1118_fu_267_p1(4 - 1 downto 0);

    b_data_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            b_data_ce0 <= ap_const_logic_1;
        else 
            b_data_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    c_data_address0_assign_proc : process(ap_CS_fsm_state3, c_data_addr_reg_364, ap_CS_fsm_state4, zext_ln122_fu_216_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            c_data_address0 <= c_data_addr_reg_364;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            c_data_address0 <= zext_ln122_fu_216_p1(4 - 1 downto 0);
        else 
            c_data_address0 <= "XXXX";
        end if; 
    end process;


    c_data_ce0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            c_data_ce0 <= ap_const_logic_1;
        else 
            c_data_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    c_data_d0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, lhs_reg_149)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            c_data_d0 <= lhs_reg_149;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            c_data_d0 <= ap_const_lv32_0;
        else 
            c_data_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    c_data_we0_assign_proc : process(cmp91_reg_336, ap_CS_fsm_state3, ap_CS_fsm_state4, icmp_ln120_fu_225_p2, icmp_ln123_fu_276_p2)
    begin
        if ((((cmp91_reg_336 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln123_fu_276_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln120_fu_225_p2 = ap_const_lv1_0)))) then 
            c_data_we0 <= ap_const_logic_1;
        else 
            c_data_we0 <= ap_const_logic_0;
        end if; 
    end process;

    cmp91_fu_162_p2 <= "1" when (signed(p_read1) > signed(ap_const_lv32_0)) else "0";
    icmp_ln118_fu_186_p2 <= "1" when (i_reg_116 = p_read) else "0";
    icmp_ln120_fu_225_p2 <= "1" when (zext_ln120_fu_221_p1 = p_read2) else "0";
    icmp_ln123_fu_276_p2 <= "1" when (zext_ln123_fu_272_p1 = p_read1) else "0";
    lhs_6_fu_295_p3 <= (lhs_reg_149 & ap_const_lv16_0);
    ret_V_fu_303_p2 <= std_logic_vector(unsigned(lhs_6_fu_295_p3) + unsigned(r_V_6_fu_289_p2));
    tmp_7_cast_fu_254_p3 <= (trunc_ln1118_fu_250_p1 & ap_const_lv2_0);
    tmp_cast_fu_178_p3 <= (trunc_ln1116_fu_174_p1 & ap_const_lv2_0);
    trunc_ln1116_2_fu_236_p1 <= k_reg_138(4 - 1 downto 0);
    trunc_ln1116_fu_174_p1 <= i_reg_116(2 - 1 downto 0);
    trunc_ln1118_fu_250_p1 <= k_reg_138(2 - 1 downto 0);
    trunc_ln122_fu_207_p1 <= j_reg_127(4 - 1 downto 0);
    zext_ln1116_fu_245_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1116_fu_240_p2),64));
    zext_ln1118_fu_267_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1118_fu_262_p2),64));
    zext_ln120_fu_221_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_reg_127),32));
    zext_ln122_fu_216_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln122_fu_211_p2),64));
    zext_ln123_fu_272_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_reg_138),32));
end behav;
