// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module kalman_hw_update_predict (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        hw_filter_timestep_i,
        hw_filter_timestep_o,
        hw_filter_timestep_o_ap_vld,
        hw_filter_state_transition_rows,
        hw_filter_state_estimate_cols,
        hw_filter_predicted_state_cols,
        hw_filter_predicted_state_cols_ap_vld,
        hw_filter_predicted_estimate_covariance_rows,
        hw_filter_predicted_estimate_covariance_rows_ap_vld,
        hw_filter_predicted_estimate_covariance_cols,
        hw_filter_predicted_estimate_covariance_cols_ap_vld,
        hw_filter_state_transition_cols,
        hw_filter_predicted_state_data_V_address0,
        hw_filter_predicted_state_data_V_ce0,
        hw_filter_predicted_state_data_V_we0,
        hw_filter_predicted_state_data_V_d0,
        hw_filter_state_transition_data_V_address0,
        hw_filter_state_transition_data_V_ce0,
        hw_filter_state_transition_data_V_q0,
        hw_filter_state_estimate_data_V_address0,
        hw_filter_state_estimate_data_V_ce0,
        hw_filter_state_estimate_data_V_q0,
        hw_filter_estimate_covariance_cols,
        hw_filter_big_square_scratch_data_V_address0,
        hw_filter_big_square_scratch_data_V_ce0,
        hw_filter_big_square_scratch_data_V_we0,
        hw_filter_big_square_scratch_data_V_d0,
        hw_filter_big_square_scratch_data_V_q0,
        hw_filter_estimate_covariance_data_V_address0,
        hw_filter_estimate_covariance_data_V_ce0,
        hw_filter_estimate_covariance_data_V_q0,
        hw_filter_predicted_estimate_covariance_data_V_address0,
        hw_filter_predicted_estimate_covariance_data_V_ce0,
        hw_filter_predicted_estimate_covariance_data_V_we0,
        hw_filter_predicted_estimate_covariance_data_V_d0,
        hw_filter_predicted_estimate_covariance_data_V_q0,
        hw_filter_process_noise_covariance_data_V_address0,
        hw_filter_process_noise_covariance_data_V_ce0,
        hw_filter_process_noise_covariance_data_V_q0
);

parameter    ap_ST_fsm_state1 = 16'd1;
parameter    ap_ST_fsm_state2 = 16'd2;
parameter    ap_ST_fsm_state3 = 16'd4;
parameter    ap_ST_fsm_state4 = 16'd8;
parameter    ap_ST_fsm_state5 = 16'd16;
parameter    ap_ST_fsm_state6 = 16'd32;
parameter    ap_ST_fsm_state7 = 16'd64;
parameter    ap_ST_fsm_state8 = 16'd128;
parameter    ap_ST_fsm_state9 = 16'd256;
parameter    ap_ST_fsm_state10 = 16'd512;
parameter    ap_ST_fsm_state11 = 16'd1024;
parameter    ap_ST_fsm_state12 = 16'd2048;
parameter    ap_ST_fsm_state13 = 16'd4096;
parameter    ap_ST_fsm_state14 = 16'd8192;
parameter    ap_ST_fsm_state15 = 16'd16384;
parameter    ap_ST_fsm_state16 = 16'd32768;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] hw_filter_timestep_i;
output  [31:0] hw_filter_timestep_o;
output   hw_filter_timestep_o_ap_vld;
input  [31:0] hw_filter_state_transition_rows;
input  [31:0] hw_filter_state_estimate_cols;
output  [31:0] hw_filter_predicted_state_cols;
output   hw_filter_predicted_state_cols_ap_vld;
output  [31:0] hw_filter_predicted_estimate_covariance_rows;
output   hw_filter_predicted_estimate_covariance_rows_ap_vld;
output  [31:0] hw_filter_predicted_estimate_covariance_cols;
output   hw_filter_predicted_estimate_covariance_cols_ap_vld;
input  [31:0] hw_filter_state_transition_cols;
output  [3:0] hw_filter_predicted_state_data_V_address0;
output   hw_filter_predicted_state_data_V_ce0;
output   hw_filter_predicted_state_data_V_we0;
output  [31:0] hw_filter_predicted_state_data_V_d0;
output  [3:0] hw_filter_state_transition_data_V_address0;
output   hw_filter_state_transition_data_V_ce0;
input  [31:0] hw_filter_state_transition_data_V_q0;
output  [3:0] hw_filter_state_estimate_data_V_address0;
output   hw_filter_state_estimate_data_V_ce0;
input  [31:0] hw_filter_state_estimate_data_V_q0;
input  [31:0] hw_filter_estimate_covariance_cols;
output  [3:0] hw_filter_big_square_scratch_data_V_address0;
output   hw_filter_big_square_scratch_data_V_ce0;
output   hw_filter_big_square_scratch_data_V_we0;
output  [31:0] hw_filter_big_square_scratch_data_V_d0;
input  [31:0] hw_filter_big_square_scratch_data_V_q0;
output  [3:0] hw_filter_estimate_covariance_data_V_address0;
output   hw_filter_estimate_covariance_data_V_ce0;
input  [31:0] hw_filter_estimate_covariance_data_V_q0;
output  [3:0] hw_filter_predicted_estimate_covariance_data_V_address0;
output   hw_filter_predicted_estimate_covariance_data_V_ce0;
output   hw_filter_predicted_estimate_covariance_data_V_we0;
output  [31:0] hw_filter_predicted_estimate_covariance_data_V_d0;
input  [31:0] hw_filter_predicted_estimate_covariance_data_V_q0;
output  [3:0] hw_filter_process_noise_covariance_data_V_address0;
output   hw_filter_process_noise_covariance_data_V_ce0;
input  [31:0] hw_filter_process_noise_covariance_data_V_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] hw_filter_timestep_o;
reg hw_filter_timestep_o_ap_vld;
reg hw_filter_predicted_state_cols_ap_vld;
reg hw_filter_predicted_estimate_covariance_rows_ap_vld;
reg hw_filter_predicted_estimate_covariance_cols_ap_vld;
reg[3:0] hw_filter_predicted_state_data_V_address0;
reg hw_filter_predicted_state_data_V_ce0;
reg hw_filter_predicted_state_data_V_we0;
reg[31:0] hw_filter_predicted_state_data_V_d0;
reg[3:0] hw_filter_state_transition_data_V_address0;
reg hw_filter_state_transition_data_V_ce0;
reg hw_filter_state_estimate_data_V_ce0;
reg[3:0] hw_filter_big_square_scratch_data_V_address0;
reg hw_filter_big_square_scratch_data_V_ce0;
reg hw_filter_big_square_scratch_data_V_we0;
reg[31:0] hw_filter_big_square_scratch_data_V_d0;
reg hw_filter_estimate_covariance_data_V_ce0;
reg[3:0] hw_filter_predicted_estimate_covariance_data_V_address0;
reg hw_filter_predicted_estimate_covariance_data_V_ce0;
reg hw_filter_predicted_estimate_covariance_data_V_we0;
reg[31:0] hw_filter_predicted_estimate_covariance_data_V_d0;
reg hw_filter_process_noise_covariance_data_V_ce0;

(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln118_fu_410_p2;
reg   [0:0] icmp_ln118_reg_932;
wire   [0:0] cmp91_i_fu_420_p2;
reg   [0:0] cmp91_i_reg_939;
wire   [30:0] trunc_ln118_fu_426_p1;
reg   [30:0] trunc_ln118_reg_943;
wire   [30:0] add_ln118_fu_430_p2;
reg   [30:0] add_ln118_reg_951;
wire    ap_CS_fsm_state2;
wire   [3:0] tmp_cast_fu_440_p3;
reg   [3:0] tmp_cast_reg_956;
wire   [4:0] add_ln120_fu_457_p2;
reg   [4:0] add_ln120_reg_968;
wire    ap_CS_fsm_state3;
wire   [3:0] trunc_ln122_2_fu_463_p1;
reg   [3:0] trunc_ln122_2_reg_973;
reg   [3:0] hw_filter_predicted_state_data_V_addr_reg_978;
wire   [30:0] add_ln123_fu_486_p2;
reg   [30:0] add_ln123_reg_986;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire   [30:0] add_ln118_1_fu_575_p2;
reg   [30:0] add_ln118_1_reg_1009;
wire    ap_CS_fsm_state6;
wire   [3:0] tmp_1_cast_fu_585_p3;
reg   [3:0] tmp_1_cast_reg_1014;
wire   [0:0] cmp53_i2_fu_598_p2;
reg   [0:0] cmp53_i2_reg_1023;
wire   [0:0] icmp_ln118_2_fu_593_p2;
wire   [4:0] add_ln120_1_fu_603_p2;
reg   [4:0] add_ln120_1_reg_1027;
wire    ap_CS_fsm_state7;
wire   [3:0] trunc_ln122_3_fu_609_p1;
reg   [3:0] trunc_ln122_3_reg_1032;
reg   [3:0] hw_filter_big_square_scratch_data_V_addr_reg_1037;
wire   [30:0] add_ln123_1_fu_632_p2;
reg   [30:0] add_ln123_1_reg_1045;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire   [30:0] add_ln136_fu_721_p2;
reg   [30:0] add_ln136_reg_1068;
wire    ap_CS_fsm_state10;
wire   [3:0] tmp_2_cast_fu_731_p3;
reg   [3:0] tmp_2_cast_reg_1073;
wire   [4:0] add_ln138_fu_744_p2;
reg   [4:0] add_ln138_reg_1082;
wire    ap_CS_fsm_state11;
reg   [3:0] hw_filter_predicted_estimate_covariance_data_V_addr_reg_1087;
wire   [3:0] tmp_4_cast_fu_768_p3;
reg   [3:0] tmp_4_cast_reg_1092;
wire   [30:0] add_ln141_fu_785_p2;
reg   [30:0] add_ln141_reg_1100;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire   [30:0] add_ln80_fu_862_p2;
reg   [30:0] add_ln80_reg_1123;
wire    ap_CS_fsm_state14;
wire   [3:0] tmp_5_cast_fu_872_p3;
reg   [3:0] tmp_5_cast_reg_1128;
wire   [4:0] add_ln82_fu_889_p2;
reg   [4:0] add_ln82_reg_1136;
wire    ap_CS_fsm_state15;
reg   [3:0] hw_filter_predicted_estimate_covariance_data_V_addr_1_reg_1141;
reg   [30:0] i_reg_208;
wire   [0:0] icmp_ln120_fu_481_p2;
reg   [4:0] j_reg_219;
wire   [0:0] icmp_ln123_fu_532_p2;
wire   [0:0] icmp_ln118_1_fu_448_p2;
reg   [30:0] k_reg_230;
reg   [31:0] lhs_reg_241;
reg   [30:0] i_1_reg_254;
wire   [0:0] icmp_ln120_1_fu_627_p2;
reg   [4:0] j_1_reg_265;
wire   [0:0] icmp_ln123_1_fu_678_p2;
reg   [30:0] k_1_reg_276;
reg   [31:0] lhs_2_reg_287;
reg   [30:0] i_2_reg_300;
wire   [0:0] icmp_ln138_fu_780_p2;
reg   [4:0] j_2_reg_311;
wire   [0:0] icmp_ln141_fu_819_p2;
wire   [0:0] icmp_ln136_fu_739_p2;
reg   [30:0] k_2_reg_322;
reg   [31:0] lhs_4_reg_333;
reg   [30:0] i_3_reg_346;
wire   [0:0] icmp_ln82_fu_914_p2;
reg   [4:0] j_3_reg_357;
wire    ap_CS_fsm_state16;
wire   [0:0] icmp_ln80_fu_884_p2;
wire   [63:0] zext_ln122_fu_472_p1;
wire   [63:0] zext_ln1118_fu_513_p1;
wire   [63:0] zext_ln1116_fu_523_p1;
wire   [63:0] zext_ln122_1_fu_618_p1;
wire   [63:0] zext_ln1118_1_fu_659_p1;
wire   [63:0] zext_ln1116_1_fu_669_p1;
wire   [63:0] zext_ln140_fu_759_p1;
wire   [63:0] zext_ln1116_2_fu_800_p1;
wire   [63:0] zext_ln1118_2_fu_810_p1;
wire   [63:0] zext_ln703_fu_904_p1;
wire   [31:0] add_ln86_fu_382_p2;
wire   [31:0] add_ln703_fu_919_p2;
wire   [1:0] trunc_ln122_fu_436_p1;
wire   [3:0] add_ln122_fu_467_p2;
wire   [31:0] zext_ln120_fu_477_p1;
wire   [1:0] trunc_ln1118_1_fu_496_p1;
wire   [3:0] tmp_3_cast_fu_500_p3;
wire   [3:0] add_ln1118_fu_508_p2;
wire   [3:0] trunc_ln1118_fu_492_p1;
wire   [3:0] add_ln1116_fu_518_p2;
wire   [31:0] zext_ln123_fu_528_p1;
wire   [47:0] lhs_1_fu_551_p3;
wire   [47:0] r_V_1_fu_545_p2;
wire   [47:0] ret_V_fu_559_p2;
wire   [1:0] trunc_ln122_1_fu_581_p1;
wire   [3:0] add_ln122_1_fu_613_p2;
wire   [31:0] zext_ln120_1_fu_623_p1;
wire   [1:0] trunc_ln1118_4_fu_642_p1;
wire   [3:0] tmp_6_cast_fu_646_p3;
wire   [3:0] add_ln1118_1_fu_654_p2;
wire   [3:0] trunc_ln1118_3_fu_638_p1;
wire   [3:0] add_ln1116_1_fu_664_p2;
wire   [31:0] zext_ln123_1_fu_674_p1;
wire   [47:0] lhs_3_fu_697_p3;
wire   [47:0] r_V_3_fu_691_p2;
wire   [47:0] ret_V_1_fu_705_p2;
wire   [1:0] trunc_ln1116_fu_727_p1;
wire   [3:0] trunc_ln140_fu_750_p1;
wire   [3:0] add_ln140_fu_754_p2;
wire   [1:0] trunc_ln1118_2_fu_764_p1;
wire   [30:0] zext_ln138_fu_776_p1;
wire   [3:0] trunc_ln1116_1_fu_791_p1;
wire   [3:0] add_ln1116_2_fu_795_p2;
wire   [3:0] add_ln1118_2_fu_805_p2;
wire   [31:0] zext_ln141_fu_815_p1;
wire   [47:0] lhs_5_fu_838_p3;
wire   [47:0] r_V_5_fu_832_p2;
wire   [47:0] ret_V_2_fu_846_p2;
wire   [1:0] trunc_ln703_fu_868_p1;
wire   [31:0] zext_ln80_fu_880_p1;
wire   [3:0] trunc_ln703_1_fu_895_p1;
wire   [3:0] add_ln703_1_fu_899_p2;
wire   [31:0] zext_ln82_fu_910_p1;
reg   [15:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'd1;
end

kalman_hw_update_mul_32s_32s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_1_1_U4(
    .din0(hw_filter_state_estimate_data_V_q0),
    .din1(hw_filter_state_transition_data_V_q0),
    .dout(r_V_1_fu_545_p2)
);

kalman_hw_update_mul_32s_32s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_1_1_U5(
    .din0(hw_filter_estimate_covariance_data_V_q0),
    .din1(hw_filter_state_transition_data_V_q0),
    .dout(r_V_3_fu_691_p2)
);

kalman_hw_update_mul_32s_32s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_1_1_U6(
    .din0(hw_filter_state_transition_data_V_q0),
    .din1(hw_filter_big_square_scratch_data_V_q0),
    .dout(r_V_5_fu_832_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln118_1_fu_448_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i_1_reg_254 <= 31'd0;
    end else if (((icmp_ln120_1_fu_627_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        i_1_reg_254 <= add_ln118_1_reg_1009;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln118_2_fu_593_p2 == 1'd1))) begin
        i_2_reg_300 <= 31'd0;
    end else if (((icmp_ln138_fu_780_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        i_2_reg_300 <= add_ln136_reg_1068;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & ((icmp_ln118_reg_932 == 1'd0) | (icmp_ln136_fu_739_p2 == 1'd1)))) begin
        i_3_reg_346 <= 31'd0;
    end else if (((icmp_ln82_fu_914_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
        i_3_reg_346 <= add_ln80_reg_1123;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln118_fu_410_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_208 <= 31'd0;
    end else if (((icmp_ln120_fu_481_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_reg_208 <= add_ln118_reg_951;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln118_2_fu_593_p2 == 1'd0))) begin
        j_1_reg_265 <= 5'd0;
    end else if (((1'b1 == ap_CS_fsm_state8) & ((cmp91_i_reg_939 == 1'd0) | (icmp_ln123_1_fu_678_p2 == 1'd1)))) begin
        j_1_reg_265 <= add_ln120_1_reg_1027;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln118_reg_932 == 1'd1) & (icmp_ln136_fu_739_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        j_2_reg_311 <= 5'd0;
    end else if (((1'b1 == ap_CS_fsm_state12) & ((icmp_ln141_fu_819_p2 == 1'd1) | (cmp53_i2_reg_1023 == 1'd0)))) begin
        j_2_reg_311 <= add_ln138_reg_1082;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln80_fu_884_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        j_3_reg_357 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        j_3_reg_357 <= add_ln82_reg_1136;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln118_1_fu_448_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_reg_219 <= 5'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & ((cmp91_i_reg_939 == 1'd0) | (icmp_ln123_fu_532_p2 == 1'd1)))) begin
        j_reg_219 <= add_ln120_reg_968;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp91_i_reg_939 == 1'd1) & (icmp_ln120_1_fu_627_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        k_1_reg_276 <= 31'd0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        k_1_reg_276 <= add_ln123_1_reg_1045;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln138_fu_780_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11) & (cmp53_i2_reg_1023 == 1'd1))) begin
        k_2_reg_322 <= 31'd0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        k_2_reg_322 <= add_ln141_reg_1100;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp91_i_reg_939 == 1'd1) & (icmp_ln120_fu_481_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        k_reg_230 <= 31'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        k_reg_230 <= add_ln123_reg_986;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp91_i_reg_939 == 1'd1) & (icmp_ln120_1_fu_627_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        lhs_2_reg_287 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        lhs_2_reg_287 <= {{ret_V_1_fu_705_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln138_fu_780_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11) & (cmp53_i2_reg_1023 == 1'd1))) begin
        lhs_4_reg_333 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        lhs_4_reg_333 <= {{ret_V_2_fu_846_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((cmp91_i_reg_939 == 1'd1) & (icmp_ln120_fu_481_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        lhs_reg_241 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        lhs_reg_241 <= {{ret_V_fu_559_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        add_ln118_1_reg_1009 <= add_ln118_1_fu_575_p2;
        tmp_1_cast_reg_1014[3 : 2] <= tmp_1_cast_fu_585_p3[3 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln118_reg_951 <= add_ln118_fu_430_p2;
        tmp_cast_reg_956[3 : 2] <= tmp_cast_fu_440_p3[3 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln120_1_reg_1027 <= add_ln120_1_fu_603_p2;
        hw_filter_big_square_scratch_data_V_addr_reg_1037 <= zext_ln122_1_fu_618_p1;
        trunc_ln122_3_reg_1032 <= trunc_ln122_3_fu_609_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln120_reg_968 <= add_ln120_fu_457_p2;
        hw_filter_predicted_state_data_V_addr_reg_978 <= zext_ln122_fu_472_p1;
        trunc_ln122_2_reg_973 <= trunc_ln122_2_fu_463_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp91_i_reg_939 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        add_ln123_1_reg_1045 <= add_ln123_1_fu_632_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp91_i_reg_939 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        add_ln123_reg_986 <= add_ln123_fu_486_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln118_reg_932 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        add_ln136_reg_1068 <= add_ln136_fu_721_p2;
        tmp_2_cast_reg_1073[3 : 2] <= tmp_2_cast_fu_731_p3[3 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        add_ln138_reg_1082 <= add_ln138_fu_744_p2;
        hw_filter_predicted_estimate_covariance_data_V_addr_reg_1087 <= zext_ln140_fu_759_p1;
        tmp_4_cast_reg_1092[3 : 2] <= tmp_4_cast_fu_768_p3[3 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (cmp53_i2_reg_1023 == 1'd1))) begin
        add_ln141_reg_1100 <= add_ln141_fu_785_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        add_ln80_reg_1123 <= add_ln80_fu_862_p2;
        tmp_5_cast_reg_1128[3 : 2] <= tmp_5_cast_fu_872_p3[3 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        add_ln82_reg_1136 <= add_ln82_fu_889_p2;
        hw_filter_predicted_estimate_covariance_data_V_addr_1_reg_1141 <= zext_ln703_fu_904_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln118_2_fu_593_p2 == 1'd1))) begin
        cmp53_i2_reg_1023 <= cmp53_i2_fu_598_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln118_fu_410_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        cmp91_i_reg_939 <= cmp91_i_fu_420_p2;
        trunc_ln118_reg_943 <= trunc_ln118_fu_426_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln118_reg_932 <= icmp_ln118_fu_410_p2;
    end
end

always @ (*) begin
    if ((((icmp_ln80_fu_884_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln80_fu_884_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        hw_filter_big_square_scratch_data_V_address0 = zext_ln1116_2_fu_800_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        hw_filter_big_square_scratch_data_V_address0 = hw_filter_big_square_scratch_data_V_addr_reg_1037;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        hw_filter_big_square_scratch_data_V_address0 = zext_ln122_1_fu_618_p1;
    end else begin
        hw_filter_big_square_scratch_data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        hw_filter_big_square_scratch_data_V_ce0 = 1'b1;
    end else begin
        hw_filter_big_square_scratch_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        hw_filter_big_square_scratch_data_V_d0 = lhs_2_reg_287;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        hw_filter_big_square_scratch_data_V_d0 = 32'd0;
    end else begin
        hw_filter_big_square_scratch_data_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln120_1_fu_627_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)) | ((cmp91_i_reg_939 == 1'd1) & (icmp_ln123_1_fu_678_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8)))) begin
        hw_filter_big_square_scratch_data_V_we0 = 1'b1;
    end else begin
        hw_filter_big_square_scratch_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        hw_filter_estimate_covariance_data_V_ce0 = 1'b1;
    end else begin
        hw_filter_estimate_covariance_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln118_fu_410_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln118_2_fu_593_p2 == 1'd1)))) begin
        hw_filter_predicted_estimate_covariance_cols_ap_vld = 1'b1;
    end else begin
        hw_filter_predicted_estimate_covariance_cols_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        hw_filter_predicted_estimate_covariance_data_V_address0 = hw_filter_predicted_estimate_covariance_data_V_addr_1_reg_1141;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        hw_filter_predicted_estimate_covariance_data_V_address0 = zext_ln703_fu_904_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        hw_filter_predicted_estimate_covariance_data_V_address0 = hw_filter_predicted_estimate_covariance_data_V_addr_reg_1087;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        hw_filter_predicted_estimate_covariance_data_V_address0 = zext_ln140_fu_759_p1;
    end else begin
        hw_filter_predicted_estimate_covariance_data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        hw_filter_predicted_estimate_covariance_data_V_ce0 = 1'b1;
    end else begin
        hw_filter_predicted_estimate_covariance_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        hw_filter_predicted_estimate_covariance_data_V_d0 = add_ln703_fu_919_p2;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        hw_filter_predicted_estimate_covariance_data_V_d0 = lhs_4_reg_333;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        hw_filter_predicted_estimate_covariance_data_V_d0 = 32'd0;
    end else begin
        hw_filter_predicted_estimate_covariance_data_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | ((icmp_ln138_fu_780_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11)) | ((icmp_ln141_fu_819_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12) & (cmp53_i2_reg_1023 == 1'd1)))) begin
        hw_filter_predicted_estimate_covariance_data_V_we0 = 1'b1;
    end else begin
        hw_filter_predicted_estimate_covariance_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln118_fu_410_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln118_2_fu_593_p2 == 1'd1)))) begin
        hw_filter_predicted_estimate_covariance_rows_ap_vld = 1'b1;
    end else begin
        hw_filter_predicted_estimate_covariance_rows_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        hw_filter_predicted_state_cols_ap_vld = 1'b1;
    end else begin
        hw_filter_predicted_state_cols_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hw_filter_predicted_state_data_V_address0 = hw_filter_predicted_state_data_V_addr_reg_978;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        hw_filter_predicted_state_data_V_address0 = zext_ln122_fu_472_p1;
    end else begin
        hw_filter_predicted_state_data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        hw_filter_predicted_state_data_V_ce0 = 1'b1;
    end else begin
        hw_filter_predicted_state_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hw_filter_predicted_state_data_V_d0 = lhs_reg_241;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        hw_filter_predicted_state_data_V_d0 = 32'd0;
    end else begin
        hw_filter_predicted_state_data_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln120_fu_481_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((cmp91_i_reg_939 == 1'd1) & (icmp_ln123_fu_532_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        hw_filter_predicted_state_data_V_we0 = 1'b1;
    end else begin
        hw_filter_predicted_state_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        hw_filter_process_noise_covariance_data_V_ce0 = 1'b1;
    end else begin
        hw_filter_process_noise_covariance_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hw_filter_state_estimate_data_V_ce0 = 1'b1;
    end else begin
        hw_filter_state_estimate_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        hw_filter_state_transition_data_V_address0 = zext_ln1118_2_fu_810_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        hw_filter_state_transition_data_V_address0 = zext_ln1116_1_fu_669_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        hw_filter_state_transition_data_V_address0 = zext_ln1116_fu_523_p1;
    end else begin
        hw_filter_state_transition_data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state4))) begin
        hw_filter_state_transition_data_V_ce0 = 1'b1;
    end else begin
        hw_filter_state_transition_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        hw_filter_timestep_o = add_ln86_fu_382_p2;
    end else begin
        hw_filter_timestep_o = hw_filter_timestep_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        hw_filter_timestep_o_ap_vld = 1'b1;
    end else begin
        hw_filter_timestep_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln118_fu_410_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((icmp_ln118_fu_410_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln118_1_fu_448_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln120_fu_481_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & ((cmp91_i_reg_939 == 1'd0) | (icmp_ln123_fu_532_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln118_2_fu_593_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((icmp_ln120_1_fu_627_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & ((cmp91_i_reg_939 == 1'd0) | (icmp_ln123_1_fu_678_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & ((icmp_ln118_reg_932 == 1'd0) | (icmp_ln136_fu_739_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((icmp_ln138_fu_780_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & ((icmp_ln141_fu_819_p2 == 1'd1) | (cmp53_i2_reg_1023 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state14 : begin
            if (((icmp_ln80_fu_884_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((icmp_ln82_fu_914_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1116_1_fu_664_p2 = (tmp_1_cast_reg_1014 + trunc_ln1118_3_fu_638_p1);

assign add_ln1116_2_fu_795_p2 = (tmp_2_cast_reg_1073 + trunc_ln1116_1_fu_791_p1);

assign add_ln1116_fu_518_p2 = (tmp_cast_reg_956 + trunc_ln1118_fu_492_p1);

assign add_ln1118_1_fu_654_p2 = (tmp_6_cast_fu_646_p3 + trunc_ln122_3_reg_1032);

assign add_ln1118_2_fu_805_p2 = (tmp_4_cast_reg_1092 + trunc_ln1116_1_fu_791_p1);

assign add_ln1118_fu_508_p2 = (tmp_3_cast_fu_500_p3 + trunc_ln122_2_reg_973);

assign add_ln118_1_fu_575_p2 = (i_1_reg_254 + 31'd1);

assign add_ln118_fu_430_p2 = (i_reg_208 + 31'd1);

assign add_ln120_1_fu_603_p2 = (j_1_reg_265 + 5'd1);

assign add_ln120_fu_457_p2 = (j_reg_219 + 5'd1);

assign add_ln122_1_fu_613_p2 = (tmp_1_cast_reg_1014 + trunc_ln122_3_fu_609_p1);

assign add_ln122_fu_467_p2 = (tmp_cast_reg_956 + trunc_ln122_2_fu_463_p1);

assign add_ln123_1_fu_632_p2 = (k_1_reg_276 + 31'd1);

assign add_ln123_fu_486_p2 = (k_reg_230 + 31'd1);

assign add_ln136_fu_721_p2 = (i_2_reg_300 + 31'd1);

assign add_ln138_fu_744_p2 = (j_2_reg_311 + 5'd1);

assign add_ln140_fu_754_p2 = (tmp_2_cast_reg_1073 + trunc_ln140_fu_750_p1);

assign add_ln141_fu_785_p2 = (k_2_reg_322 + 31'd1);

assign add_ln703_1_fu_899_p2 = (tmp_5_cast_reg_1128 + trunc_ln703_1_fu_895_p1);

assign add_ln703_fu_919_p2 = (hw_filter_process_noise_covariance_data_V_q0 + hw_filter_predicted_estimate_covariance_data_V_q0);

assign add_ln80_fu_862_p2 = (i_3_reg_346 + 31'd1);

assign add_ln82_fu_889_p2 = (j_3_reg_357 + 5'd1);

assign add_ln86_fu_382_p2 = (hw_filter_timestep_i + 32'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign cmp53_i2_fu_598_p2 = (($signed(hw_filter_estimate_covariance_cols) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign cmp91_i_fu_420_p2 = (($signed(hw_filter_state_transition_cols) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign hw_filter_estimate_covariance_data_V_address0 = zext_ln1118_1_fu_659_p1;

assign hw_filter_predicted_estimate_covariance_cols = hw_filter_state_transition_rows;

assign hw_filter_predicted_estimate_covariance_rows = hw_filter_state_transition_rows;

assign hw_filter_predicted_state_cols = hw_filter_state_estimate_cols;

assign hw_filter_process_noise_covariance_data_V_address0 = zext_ln703_fu_904_p1;

assign hw_filter_state_estimate_data_V_address0 = zext_ln1118_fu_513_p1;

assign icmp_ln118_1_fu_448_p2 = ((i_reg_208 == trunc_ln118_reg_943) ? 1'b1 : 1'b0);

assign icmp_ln118_2_fu_593_p2 = ((i_1_reg_254 == trunc_ln118_reg_943) ? 1'b1 : 1'b0);

assign icmp_ln118_fu_410_p2 = (($signed(hw_filter_state_transition_rows) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln120_1_fu_627_p2 = ((zext_ln120_1_fu_623_p1 == hw_filter_estimate_covariance_cols) ? 1'b1 : 1'b0);

assign icmp_ln120_fu_481_p2 = ((zext_ln120_fu_477_p1 == hw_filter_state_estimate_cols) ? 1'b1 : 1'b0);

assign icmp_ln123_1_fu_678_p2 = ((zext_ln123_1_fu_674_p1 == hw_filter_state_transition_cols) ? 1'b1 : 1'b0);

assign icmp_ln123_fu_532_p2 = ((zext_ln123_fu_528_p1 == hw_filter_state_transition_cols) ? 1'b1 : 1'b0);

assign icmp_ln136_fu_739_p2 = ((i_2_reg_300 == trunc_ln118_reg_943) ? 1'b1 : 1'b0);

assign icmp_ln138_fu_780_p2 = ((zext_ln138_fu_776_p1 == trunc_ln118_reg_943) ? 1'b1 : 1'b0);

assign icmp_ln141_fu_819_p2 = ((zext_ln141_fu_815_p1 == hw_filter_estimate_covariance_cols) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_884_p2 = (($signed(zext_ln80_fu_880_p1) < $signed(hw_filter_state_transition_rows)) ? 1'b1 : 1'b0);

assign icmp_ln82_fu_914_p2 = ((zext_ln82_fu_910_p1 == hw_filter_state_transition_rows) ? 1'b1 : 1'b0);

assign lhs_1_fu_551_p3 = {{lhs_reg_241}, {16'd0}};

assign lhs_3_fu_697_p3 = {{lhs_2_reg_287}, {16'd0}};

assign lhs_5_fu_838_p3 = {{lhs_4_reg_333}, {16'd0}};

assign ret_V_1_fu_705_p2 = (lhs_3_fu_697_p3 + r_V_3_fu_691_p2);

assign ret_V_2_fu_846_p2 = (lhs_5_fu_838_p3 + r_V_5_fu_832_p2);

assign ret_V_fu_559_p2 = (lhs_1_fu_551_p3 + r_V_1_fu_545_p2);

assign tmp_1_cast_fu_585_p3 = {{trunc_ln122_1_fu_581_p1}, {2'd0}};

assign tmp_2_cast_fu_731_p3 = {{trunc_ln1116_fu_727_p1}, {2'd0}};

assign tmp_3_cast_fu_500_p3 = {{trunc_ln1118_1_fu_496_p1}, {2'd0}};

assign tmp_4_cast_fu_768_p3 = {{trunc_ln1118_2_fu_764_p1}, {2'd0}};

assign tmp_5_cast_fu_872_p3 = {{trunc_ln703_fu_868_p1}, {2'd0}};

assign tmp_6_cast_fu_646_p3 = {{trunc_ln1118_4_fu_642_p1}, {2'd0}};

assign tmp_cast_fu_440_p3 = {{trunc_ln122_fu_436_p1}, {2'd0}};

assign trunc_ln1116_1_fu_791_p1 = k_2_reg_322[3:0];

assign trunc_ln1116_fu_727_p1 = i_2_reg_300[1:0];

assign trunc_ln1118_1_fu_496_p1 = k_reg_230[1:0];

assign trunc_ln1118_2_fu_764_p1 = j_2_reg_311[1:0];

assign trunc_ln1118_3_fu_638_p1 = k_1_reg_276[3:0];

assign trunc_ln1118_4_fu_642_p1 = k_1_reg_276[1:0];

assign trunc_ln1118_fu_492_p1 = k_reg_230[3:0];

assign trunc_ln118_fu_426_p1 = hw_filter_state_transition_rows[30:0];

assign trunc_ln122_1_fu_581_p1 = i_1_reg_254[1:0];

assign trunc_ln122_2_fu_463_p1 = j_reg_219[3:0];

assign trunc_ln122_3_fu_609_p1 = j_1_reg_265[3:0];

assign trunc_ln122_fu_436_p1 = i_reg_208[1:0];

assign trunc_ln140_fu_750_p1 = j_2_reg_311[3:0];

assign trunc_ln703_1_fu_895_p1 = j_3_reg_357[3:0];

assign trunc_ln703_fu_868_p1 = i_3_reg_346[1:0];

assign zext_ln1116_1_fu_669_p1 = add_ln1116_1_fu_664_p2;

assign zext_ln1116_2_fu_800_p1 = add_ln1116_2_fu_795_p2;

assign zext_ln1116_fu_523_p1 = add_ln1116_fu_518_p2;

assign zext_ln1118_1_fu_659_p1 = add_ln1118_1_fu_654_p2;

assign zext_ln1118_2_fu_810_p1 = add_ln1118_2_fu_805_p2;

assign zext_ln1118_fu_513_p1 = add_ln1118_fu_508_p2;

assign zext_ln120_1_fu_623_p1 = j_1_reg_265;

assign zext_ln120_fu_477_p1 = j_reg_219;

assign zext_ln122_1_fu_618_p1 = add_ln122_1_fu_613_p2;

assign zext_ln122_fu_472_p1 = add_ln122_fu_467_p2;

assign zext_ln123_1_fu_674_p1 = k_1_reg_276;

assign zext_ln123_fu_528_p1 = k_reg_230;

assign zext_ln138_fu_776_p1 = j_2_reg_311;

assign zext_ln140_fu_759_p1 = add_ln140_fu_754_p2;

assign zext_ln141_fu_815_p1 = k_2_reg_322;

assign zext_ln703_fu_904_p1 = add_ln703_1_fu_899_p2;

assign zext_ln80_fu_880_p1 = i_3_reg_346;

assign zext_ln82_fu_910_p1 = j_3_reg_357;

always @ (posedge ap_clk) begin
    tmp_cast_reg_956[1:0] <= 2'b00;
    tmp_1_cast_reg_1014[1:0] <= 2'b00;
    tmp_2_cast_reg_1073[1:0] <= 2'b00;
    tmp_4_cast_reg_1092[1:0] <= 2'b00;
    tmp_5_cast_reg_1128[1:0] <= 2'b00;
end

endmodule //kalman_hw_update_predict
